Feature: Verify the Lineage cases in API and UI for the Postgres Post Processor Plugin


  #####################Add Credentials for Postgres plugin####################################################

  Scenario Outline:SC1#Add valid Credentials for Postgres
    Given endpoint for "<ServiceName>" for "<ServiceUser>" having "<Header>" and query param with "<Query>" "<Param>" for request type "<type>" with url "<url>" and body "<body>" and verify "<response code>" and "<response message>" using "<jsonPath>"
    Examples:
      | ServiceName | ServiceUser    | Header           | Query | Param | type | url                                       | body                                                       | response code | response message | jsonPath |
      | IDC         | TestSystemUser | application/json | raw   | false | Put  | settings/credentials/Postgres_Credentials | ida/PostgresPostprocessorPayloads/PostgresCredentials.json | 200           |                  |          |
      | IDC         | TestSystemUser | application/json |       |       | Get  | settings/credentials/Postgres_Credentials |                                                            | 200           |                  |          |
      | IDC         | TestSystemUser | application/json |       |       | Post | items/Default/root                        | ida/PostgresPostprocessorPayloads/BusinessApplication.json | 200           |                  |          |

    ##########################################Run the Postgres Cataloger and Post Processor#########################################

  Scenario Outline:SC2#Run the PostgresDB Cataloger and PostProcessor Plugins
    Given endpoint for "<ServiceName>" for "<ServiceUser>" having "<Header>" and query param with "<Query>" "<Param>" for request type "<type>" with url "<url>" and body "<body>" and verify "<response code>" and "<response message>" using "<jsonPath>"
    Examples:
      | ServiceName | ServiceUser    | Header           | Query | Param | type         | url                                                                          | body                                                         | response code | response message       | jsonPath                                                    |
      | IDC         | TestSystemUser | application/json | raw   | false | Put          | settings/analyzers/PostgreSQLDBDataSource                                    | ida/PostgresPostprocessorPayloads/PostgresDataSource.json    | 204           |                        |                                                             |
      | IDC         | TestSystemUser | application/json | raw   | false | Get          | settings/analyzers/PostgreSQLDBDataSource                                    |                                                              | 200           | PostgresDS             |                                                             |
      | IDC         | TestSystemUser | application/json | raw   | false | Put          | settings/analyzers/PostgreSQLDBCataloger                                     | ida/PostgresPostprocessorPayloads/PostgresCataloger.json     | 204           |                        |                                                             |
      | IDC         | TestSystemUser | application/json | raw   | false | Get          | settings/analyzers/PostgreSQLDBCataloger                                     |                                                              | 200           | Postgres_Cataloger     |                                                             |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/LocalNode/cataloger/PostgreSQLDBCataloger/*      |                                                              | 200           | IDLE                   | $.[?(@.configurationName=='Postgres_Cataloger')].status     |
      | IDC         | TestSystemUser | application/json | raw   | false | Post         | extensions/analyzers/start/LocalNode/cataloger/PostgreSQLDBCataloger/*       | ida/PostgresPostprocessorPayloads/empty.json                 | 200           |                        |                                                             |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/LocalNode/cataloger/PostgreSQLDBCataloger/*      |                                                              | 200           | IDLE                   | $.[?(@.configurationName=='Postgres_Cataloger')].status     |
      | IDC         | TestSystemUser | application/json | raw   | false | Put          | settings/analyzers/PostgreSQLDBPostProcessor                                 | ida/PostgresPostprocessorPayloads/PostgresPostProcessor.json | 204           |                        |                                                             |
      | IDC         | TestSystemUser | application/json | raw   | false | Get          | settings/analyzers/PostgreSQLDBPostProcessor                                 |                                                              | 200           | Postgres_Postprocessor |                                                             |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/InternalNode/lineage/PostgreSQLDBPostProcessor/* |                                                              | 200           | IDLE                   | $.[?(@.configurationName=='Postgres_Postprocessor')].status |
      | IDC         | TestSystemUser | application/json | raw   | false | Post         | extensions/analyzers/start/InternalNode/lineage/PostgreSQLDBPostProcessor/*  | ida/PostgresPostprocessorPayloads/empty.json                 | 200           |                        |                                                             |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/InternalNode/lineage/PostgreSQLDBPostProcessor/* |                                                              | 200           | IDLE                   | $.[?(@.configurationName=='Postgres_Postprocessor')].status |

#################################################On Prem########################################################################################################################################################################################################################################################
    #################################Verify Processed count, items and Logging enhancement for Oracle19cPDB##################################################################

  #7152587
  @webtest
  Scenario: SC#3_1_Verify the Postgre Postprocessor Plugin Processed Items
    Given User launch browser and traverse to login page
    And user enter credentials for "System Administrator1" role
    And user enters the search text "PostgreSQLDBPostProcessor" and clicks on search
    And user performs "facet selection" in "Analysis" attribute under "Metadata Type" facets in Item Search results page
    And user performs "latest analysis click" in Item Results page for "lineage/PostgreSQLDBPostProcessor/Postgres_Postprocessor%"
    Then the following metadata values should be displayed
      | metaDataAttribute         | metaDataValue | widgetName  |
      | Number of processed items | 2             | Description |
      | Number of errors          | 0             | Description |
    And user "verifies tab section values" has the following values in "Processed Items" Tab in Item View page
      | PostgreSQL              |
      | dechewindock01v.asg.com |

   #7152587
  @webtest
  Scenario: SC#3_2_Verify the Logging enhancement in PostgreSQLDB Postprocessor
    Given User launch browser and traverse to login page
    And user enter credentials for "System Administrator1" role
    And user enters the search text "PostgreSQLDBPostProcessor" and clicks on search
    And user performs "facet selection" in "Analysis" attribute under "Metadata Type" facets in Item Search results page
    And user performs "latest analysis click" in Item Results page for "lineage/PostgreSQLDBPostProcessor/Postgres_Postprocessor%"
    Then Analysis log "lineage/PostgreSQLDBPostProcessor/Postgres_Postprocessor%" should display below info/error/warning
      | type | logValue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | logCode       | pluginName                | removableText  |
      | INFO | Plugin started                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | ANALYSIS-0019 |                           |                |
      | INFO | Plugin Name:PostgreSQLDBPostProcessor, Plugin Type:lineage, Plugin Version:1.1.0.SNAPSHOT, Node Name:InternalNode, Host Name:a3d5873bf4e6, Plugin Configuration name:Postgres_Postprocessor                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | ANALYSIS-0071 | PostgreSQLDBPostProcessor | Plugin Version |
      | INFO | Plugin PostgreSQLDBPostProcessor Configuration: ---  2020-08-07 02:47:07.414 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: name: "Postgres_Postprocessor"  2020-08-07 02:47:07.414 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: pluginVersion: "LATEST"  2020-08-07 02:47:07.414 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: label:  2020-08-07 02:47:07.414 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: : ""  2020-08-07 02:47:07.415 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: catalogName: "Default"  2020-08-07 02:47:07.415 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: eventClass: null  2020-08-07 02:47:07.423 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: eventCondition: null  2020-08-07 02:47:07.423 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: nodeCondition: "name==\"InternalNode\""  2020-08-07 02:47:07.423 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: maxWorkSize: 100  2020-08-07 02:47:07.423 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: tags: []  2020-08-07 02:47:07.423 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: pluginType: "lineage"  2020-08-07 02:47:07.423 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: dataSource: null  2020-08-07 02:47:07.423 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: credential: null  2020-08-07 02:47:07.424 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: businessApplicationName: null  2020-08-07 02:47:07.424 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: dryRun: false  2020-08-07 02:47:07.424 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: schedule: null  2020-08-07 02:47:07.424 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: runAfter: []  2020-08-07 02:47:07.424 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: filter: null  2020-08-07 02:47:07.424 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: pluginName: "PostgreSQLDBPostProcessor"  2020-08-07 02:47:07.424 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: arguments: []  2020-08-07 02:47:07.424 INFO  - ANALYSIS-0073: Plugin PostgreSQLDBPostProcessor Configuration: type: "Lineage" | ANALYSIS-0073 | PostgreSQLDBPostProcessor |                |
      | INFO | ANALYSIS-0072: Plugin PostgreSQLDBPostProcessor Start Time:2020-08-07 02:47:07.412, End Time:2020-08-07 02:47:12.187, Processed Count:2, Errors:0, Warnings:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | ANALYSIS-0072 | PostgreSQLDBPostProcessor |                |
      | INFO | Plugin completed (elapsed time in (HH:MM:SS.ms): 00:00:04.775)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | ANALYSIS-0020 |                           |                |

    ####################################################Lineage Verification in API##########################################################################################################

  ##7147416## ##7147417## ##7147418## ##7147419## ##7147420## ##7147421## ##7147422## ##7147423## ##7147424## ##7147425## ##7147426## ##7147427##
  Scenario:SC#4-1_user get all lineage hops id,s and get the source target value from database
    Given user retrieves all lineage hops values for below parameters
      | database      | retrive              | catalog | type  | lineageFlow  | name                                                | asg_scopeid | targetFile                                                       | jsonpath |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | Postgressviewtosingletable                          |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | Postgressviewtomultipletable                        |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | person_detail_job_vw                                |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | managertreerecursive                                |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | postgressmaterializedviewwithdata                   |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | postgressmaterializedviewwithnodata                 |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | cityviewwithcheckoption                             |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | childcityview1                                      |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | PostgressViewToViewAndViewToTable                   |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | PostgressViewToMultipleTableInnerJoin               |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | PostgressViewToMultipleTableWithJoinDiffSchema      |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | PostgressViewToMultipleTableWithJoinhavingCondition |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewToMultipleTableGroupbyHaving                |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
    And user hits the following API with given parameters and store the api response in file
      | ServiceName | ServiceUser    | Header           | Query | Param | type | url                                                                                     | bodyFile                                                         | path                                                                  | response code | response message | jsonPath | targetFile                                                                  |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.Postgressviewtosingletable                          | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.Postgressviewtomultipletable                        | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.person_detail_job_vw                                | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.managertreerecursive                                | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.postgressmaterializedviewwithdata                   | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.postgressmaterializedviewwithnodata                 | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.cityviewwithcheckoption                             | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.childcityview1                                      | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.PostgressViewToViewAndViewToTable                   | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.PostgressViewToMultipleTableInnerJoin               | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.PostgressViewToMultipleTableWithJoinDiffSchema      | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.PostgressViewToMultipleTableWithJoinhavingCondition | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.SnowViewToMultipleTableGroupbyHaving                | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops.json |
    And user retrieves the name of each id stored in files with below parameters
      | fileName                                                                                      | JsonPath                                            |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops.json | Postgressviewtosingletable                          |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops.json | Postgressviewtomultipletable                        |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops.json | person_detail_job_vw                                |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops.json | managertreerecursive                                |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops.json | postgressmaterializedviewwithdata                   |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops.json | postgressmaterializedviewwithnodata                 |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops.json | cityviewwithcheckoption                             |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops.json | childcityview1                                      |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops.json | PostgressViewToViewAndViewToTable                   |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops.json | PostgressViewToMultipleTableInnerJoin               |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops.json | PostgressViewToMultipleTableWithJoinDiffSchema      |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops.json | PostgressViewToMultipleTableWithJoinhavingCondition |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops.json | SnowViewToMultipleTableGroupbyHaving                |

    #Bug id for Testcase ##7147419## - MLP-26012
    ##7147416## ##7147417## ##7147418## ##7147419## ##7147420## ##7147421## ##7147422## ##7147423## ##7147424## ##7147425## ##7147426## ##7147427##
  Scenario Outline:SC#4-2_user compares the expected lineage data and actual lineage data
    Given user json assert between "<expectedJson>" data and "<actualJson>" data
    Examples:
      | expectedJson                                                                                      | actualJson                                                                                    |
      | Constant.REST_DIR/response/PostgrePostProcessor/expectedJsonFiles/expectedPostgreLineageHops.json | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops.json |

  Scenario:SC#4-3 Delete Cluster and all the Analysis log for Postgres
    And Delete multiple values in IDC UI with below parameters
      | deleteAction     | catalog | name                                                      | type     | query | param |
      | SingleItemDelete | Default | dechewindock01v.asg.com                                   | Cluster  |       |       |
      | SingleItemDelete | Default | cataloger/PostgreSQLDBCataloger/Postgres_Cataloger/%      | Analysis |       |       |
      | SingleItemDelete | Default | lineage/PostgreSQLDBPostProcessor/Postgres_Postprocessor% | Analysis |       |       |

################################################# RDS ########################################################################################################################################################################################################################################################
  ################################################# Mandatory field check in DataSource ##################################################################################################################################################################################################################################

  #7151257
  @webtest
  Scenario:SC#5_Verify JDBC driver need to be uploaded separately and Bundle Name appears as mandatory field in DataSource.
    Given User launch browser and traverse to login page
    When user enter credentials for "System Administrator1" role
    And user performs following actions in the sidebar
      | actionType | actionItem                                         |
      | click      | Settings Icon                                      |
      | click      | Manage Data Sources                                |
      | click      | Add Data Source Button in Manage Data Sources Page |
    And user "select dropdown" in Add Configuration Page in Manage Configurations
      | fieldName        | attribute              |
      | Data Source Type | PostgreSQLDBDataSource |
    And user should scroll to the left of the screen
    Then user "Verify the presnce of captions" in Plugin Configuration page
      | Driver Bundle Name* |

    ############################################Dry Run for PostgreSQLDB Postprocessor######################################

  #7152587
  Scenario Outline:SC6#Run the PostgresDB Cataloger and PostProcessor Plugins
    Given endpoint for "<ServiceName>" for "<ServiceUser>" having "<Header>" and query param with "<Query>" "<Param>" for request type "<type>" with url "<url>" and body "<body>" and verify "<response code>" and "<response message>" using "<jsonPath>"
    Examples:
      | ServiceName | ServiceUser    | Header           | Query | Param | type         | url                                                                          | body                                                                | response code | response message              | jsonPath                                                           |
      | IDC         | TestSystemUser | application/json | raw   | false | Put          | settings/analyzers/PostgreSQLDBDataSource                                    | ida/PostgresPostprocessorPayloads/PostgresDataSource.json           | 204           |                               |                                                                    |
      | IDC         | TestSystemUser | application/json | raw   | false | Get          | settings/analyzers/PostgreSQLDBDataSource                                    |                                                                     | 200           | PostgresDS                    |                                                                    |
      | IDC         | TestSystemUser | application/json | raw   | false | Put          | settings/analyzers/PostgreSQLDBCataloger                                     | ida/PostgresPostprocessorPayloads/PostgresCataloger.json            | 204           |                               |                                                                    |
      | IDC         | TestSystemUser | application/json | raw   | false | Get          | settings/analyzers/PostgreSQLDBCataloger                                     |                                                                     | 200           | Postgres_Cataloger            |                                                                    |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/LocalNode/cataloger/PostgreSQLDBCataloger/*      |                                                                     | 200           | IDLE                          | $.[?(@.configurationName=='Postgres_Cataloger')].status            |
      | IDC         | TestSystemUser | application/json | raw   | false | Post         | extensions/analyzers/start/LocalNode/cataloger/PostgreSQLDBCataloger/*       | ida/PostgresPostprocessorPayloads/empty.json                        | 200           |                               |                                                                    |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/LocalNode/cataloger/PostgreSQLDBCataloger/*      |                                                                     | 200           | IDLE                          | $.[?(@.configurationName=='Postgres_Cataloger')].status            |
      | IDC         | TestSystemUser | application/json | raw   | false | Put          | settings/analyzers/PostgreSQLDBPostProcessor                                 | ida/PostgresPostprocessorPayloads/PostgresPostProcessor_DryRun.json | 204           |                               |                                                                    |
      | IDC         | TestSystemUser | application/json | raw   | false | Get          | settings/analyzers/PostgreSQLDBPostProcessor                                 |                                                                     | 200           | Postgres_Postprocessor_DryRun |                                                                    |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/InternalNode/lineage/PostgreSQLDBPostProcessor/* |                                                                     | 200           | IDLE                          | $.[?(@.configurationName=='Postgres_Postprocessor_DryRun')].status |
      | IDC         | TestSystemUser | application/json | raw   | false | Post         | extensions/analyzers/start/InternalNode/lineage/PostgreSQLDBPostProcessor/*  | ida/PostgresPostprocessorPayloads/empty.json                        | 200           |                               |                                                                    |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/InternalNode/lineage/PostgreSQLDBPostProcessor/* |                                                                     | 200           | IDLE                          | $.[?(@.configurationName=='Postgres_Postprocessor_DryRun')].status |

   #Bug - MLP-24577 #7152587
  @webtest
  Scenario:SC#6-1_Verify the Dry run feature for the PostgreSQLDB PostProcessor
    And User launch browser and traverse to login page
    And user enter credentials for "System Administrator1" role
    And user enters the search text "PostgreSQLDBPostProcessor" and clicks on search
    And user performs "facet selection" in "Analysis" attribute under "Metadata Type" facets in Item Search results page
    And user performs "latest analysis click" in Item Results page for "lineage/PostgreSQLDBPostProcessor/Postgres_Postprocessor_DryRun%"
    Then the following metadata values should be displayed
      | metaDataAttribute         | metaDataValue | widgetName  |
      | Number of processed items | 0             | Description |
      | Number of errors          | 0             | Description |
    And user "widget not present" on "Processed Items" in Item view page
    Then Analysis log "lineage/PostgreSQLDBPostProcessor/Postgres_Postprocessor_DryRun%" should display below info/error/warning
      | type | logValue                                                                                             | logCode       | pluginName                | removableText |
      | INFO | Plugin PostgreSQLDBPostProcessor running on dry run mode                                             | ANALYSIS-0069 | PostgreSQLDBPostProcessor |               |
      | INFO | Plugin PostgreSQLDBPostProcessor processed 2 items on dry run mode and not written to the repository | ANALYSIS-0070 | PostgreSQLDBPostProcessor |               |
      | INFO | Plugin completed                                                                                     | ANALYSIS-0020 |                           |               |

  Scenario:SC#6-2 Delete Cluster and all the Analysis log for Postgres
    And Delete multiple values in IDC UI with below parameters
      | deleteAction     | catalog | name                                                      | type     | query | param |
      | SingleItemDelete | Default | dechewindock01v.asg.com                                   | Cluster  |       |       |
      | SingleItemDelete | Default | cataloger/PostgreSQLDBCataloger/Postgres_Cataloger/%      | Analysis |       |       |
      | SingleItemDelete | Default | lineage/PostgreSQLDBPostProcessor/Postgres_Postprocessor% | Analysis |       |       |

##########################################Run the Postgres Cataloger and Post Processor#########################################

  Scenario Outline:SC7#Run the PostgresDB Cataloger and PostProcessor Plugins
    Given endpoint for "<ServiceName>" for "<ServiceUser>" having "<Header>" and query param with "<Query>" "<Param>" for request type "<type>" with url "<url>" and body "<body>" and verify "<response code>" and "<response message>" using "<jsonPath>"
    Examples:
      | ServiceName | ServiceUser    | Header           | Query | Param | type         | url                                                                          | body                                                          | response code | response message       | jsonPath                                                    |
      | IDC         | TestSystemUser | application/json | raw   | false | Put          | settings/analyzers/PostgreSQLDBDataSource                                    | ida/PostgresPostprocessorPayloads/PostgresDataSource_RDS.json | 204           |                        |                                                             |
      | IDC         | TestSystemUser | application/json | raw   | false | Get          | settings/analyzers/PostgreSQLDBDataSource                                    |                                                               | 200           | PostgresDS             |                                                             |
      | IDC         | TestSystemUser | application/json | raw   | false | Put          | settings/analyzers/PostgreSQLDBCataloger                                     | ida/PostgresPostprocessorPayloads/PostgresCataloger.json      | 204           |                        |                                                             |
      | IDC         | TestSystemUser | application/json | raw   | false | Get          | settings/analyzers/PostgreSQLDBCataloger                                     |                                                               | 200           | Postgres_Cataloger     |                                                             |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/LocalNode/cataloger/PostgreSQLDBCataloger/*      |                                                               | 200           | IDLE                   | $.[?(@.configurationName=='Postgres_Cataloger')].status     |
      | IDC         | TestSystemUser | application/json | raw   | false | Post         | extensions/analyzers/start/LocalNode/cataloger/PostgreSQLDBCataloger/*       | ida/PostgresPostprocessorPayloads/empty.json                  | 200           |                        |                                                             |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/LocalNode/cataloger/PostgreSQLDBCataloger/*      |                                                               | 200           | IDLE                   | $.[?(@.configurationName=='Postgres_Cataloger')].status     |
      | IDC         | TestSystemUser | application/json | raw   | false | Put          | settings/analyzers/PostgreSQLDBPostProcessor                                 | ida/PostgresPostprocessorPayloads/PostgresPostProcessor.json  | 204           |                        |                                                             |
      | IDC         | TestSystemUser | application/json | raw   | false | Get          | settings/analyzers/PostgreSQLDBPostProcessor                                 |                                                               | 200           | Postgres_Postprocessor |                                                             |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/InternalNode/lineage/PostgreSQLDBPostProcessor/* |                                                               | 200           | IDLE                   | $.[?(@.configurationName=='Postgres_Postprocessor')].status |
      | IDC         | TestSystemUser | application/json | raw   | false | Post         | extensions/analyzers/start/InternalNode/lineage/PostgreSQLDBPostProcessor/*  | ida/PostgresPostprocessorPayloads/empty.json                  | 200           |                        |                                                             |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/InternalNode/lineage/PostgreSQLDBPostProcessor/* |                                                               | 200           | IDLE                   | $.[?(@.configurationName=='Postgres_Postprocessor')].status |

    ##7147428## ##7147429## ##7147430## ##7147431## ##7147432## ##7147433## ##7147434## ##7147435## ##7147436## ##7147437## ##7147438## ##7147439## ##7149740##
  Scenario:SC#7-1_user get all lineage hops id,s and get the source target value from database
    Given user retrieves all lineage hops values for below parameters
      | database      | retrive              | catalog | type  | lineageFlow  | name                                 | asg_scopeid | targetFile                                                       | jsonpath |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | PostgressViewWithUnion               |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | PostgressViewWithUnionAll            |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | PostgressViewLeftOuterjoin           |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | PostViewRightOuterjoin               |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | PostViewFullOuterjoin                |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | PostViewFullCrossjoin                |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | PostgressViewSubqueryUsingWhere      |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | postgressviewsubqueryusingwhereexist |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | PostgressViewFromComplexStatement    |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | postgresscitycomplexview             |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | postgressviewdomainudt               |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | testmultiplecolumnview               |             | response/PostgrePostProcessor/actualJsonFiles/lineageHopIDs.json |          |
    And user hits the following API with given parameters and store the api response in file
      | ServiceName | ServiceUser    | Header           | Query | Param | type | url                                                                                     | bodyFile                                                         | path                                                   | response code | response message | jsonPath | targetFile                                                                      |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.PostgressViewWithUnion               | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops_RDS.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.PostgressViewWithUnionAll            | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops_RDS.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.PostgressViewLeftOuterjoin           | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops_RDS.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.PostViewRightOuterjoin               | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops_RDS.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.PostViewFullOuterjoin                | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops_RDS.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.PostViewFullCrossjoin                | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops_RDS.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.PostgressViewSubqueryUsingWhere      | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops_RDS.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.postgressviewsubqueryusingwhereexist | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops_RDS.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.PostgressViewFromComplexStatement    | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops_RDS.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.postgresscitycomplexview             | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops_RDS.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.postgressviewdomainudt               | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops_RDS.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=OUT&lineageDepth=0&exclude=MULTIHOP&excludeUnusedViewColumns=false | response\PostgrePostProcessor\actualJsonFiles\lineageHopIDs.json | $.lineagePayLoads.testmultiplecolumnview               | 200           |                  | edges    | response\PostgrePostProcessor\actualJsonFiles\actualPostgreLineageHops_RDS.json |
    And user retrieves the name of each id stored in files with below parameters
      | fileName                                                                                          | JsonPath                             |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops_RDS.json | PostgressViewWithUnion               |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops_RDS.json | PostgressViewWithUnionAll            |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops_RDS.json | PostgressViewLeftOuterjoin           |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops_RDS.json | PostViewRightOuterjoin               |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops_RDS.json | PostViewFullOuterjoin                |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops_RDS.json | PostViewFullCrossjoin                |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops_RDS.json | PostgressViewSubqueryUsingWhere      |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops_RDS.json | postgressviewsubqueryusingwhereexist |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops_RDS.json | PostgressViewFromComplexStatement    |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops_RDS.json | postgresscitycomplexview             |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops_RDS.json | postgressviewdomainudt               |
      | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops_RDS.json | testmultiplecolumnview               |


    ##7147428## ##7147429## ##7147430## ##7147431## ##7147432## ##7147433## ##7147434## ##7147435## ##7147436## ##7147437## ##7147438## ##7147439## ##7149740##
  Scenario Outline:SC#7-2_user compares the expected lineage data and actual lineage data
    Given user json assert between "<expectedJson>" data and "<actualJson>" data
    Examples:
      | expectedJson                                                                                          | actualJson                                                                                        |
      | Constant.REST_DIR/response/PostgrePostProcessor/expectedJsonFiles/expectedPostgreLineageHops_RDS.json | Constant.REST_DIR/response/PostgrePostProcessor/actualJsonFiles/actualPostgreLineageHops_RDS.json |

  Scenario:SC#7-3 Delete Cluster and all the Analysis log for Postgres
    And Delete multiple values in IDC UI with below parameters
      | deleteAction     | catalog | name                                                      | type     | query | param |
      | SingleItemDelete | Default | ddpostgresql.cshey0cobobn.us-east-1.rds.amazonaws.com     | Cluster  |       |       |
      | SingleItemDelete | Default | cataloger/PostgreSQLDBCataloger/Postgres_Cataloger/%      | Analysis |       |       |
      | SingleItemDelete | Default | lineage/PostgreSQLDBPostProcessor/Postgres_Postprocessor% | Analysis |       |       |

#########################################################Delete Credentials and Plugin config##############################################################################################################################################################################################################################################

  Scenario Outline: SC#8 Delete the credentials for PostgreSQLDB
    Given endpoint for "<ServiceName>" for "<ServiceUser>" having "<Header>" and query param with "<Query>" "<Param>" for request type "<type>" with url "<url>" and body "<body>" and verify "<response code>" and "<response message>" using "<jsonPath>"
    Examples:
      | ServiceName | ServiceUser    | Header           | Query | Param | type   | url                                       | body | response code | response message | jsonPath |
      | IDC         | TestSystemUser | application/json | raw   | false | Delete | settings/credentials/Postgres_Credentials |      | 200           |                  |          |
      | IDC         | TestSystemUser | application/json | raw   | false | Delete | settings/analyzers/PostgreSQLDBCataloger  |      | 204           |                  |          |
      | IDC         | TestSystemUser | application/json | raw   | false | Delete | settings/analyzers/PostgreSQLDBDataSource |      | 204           |                  |          |