Feature: Verify the Lineage cases in API and UI for the SQLServer Postprocessor plugin for RDS


##################### Add Credentials for SQlServer Postprocessor ####################################################


  @precondition
  Scenario: SC#1_Update credential payload json for SqlServerDB
    Given User update the below "RDS SqlServer Credentials readOnly" in following files using json path
      | filePath                                                               | username    | password    |
      | ida/SqlServerPostprocessorPayloads_2019/SqlServer_Credentials_RDS.json | $..userName | $..password |


  @sanity @positive @regression @IDA_E2E
  Scenario Outline: SC#1_2_Add valid Credentials for SqlServerDB
    Given endpoint for "<ServiceName>" for "<ServiceUser>" having "<Header>" and query param with "<Query>" "<Param>" for request type "<type>" with url "<url>" and body "<body>" and verify "<response code>" and "<response message>" using "<jsonPath>"
    Examples:
      | ServiceName | ServiceUser    | Header           | Query | Param | type | url                                        | body                                                                   | response code | response message | jsonPath |
      | IDC         | TestSystemUser | application/json | raw   | false | Put  | settings/credentials/SqlServer_Credentials | ida/SqlServerPostprocessorPayloads_2019/SqlServer_Credentials_RDS.json | 200           |                  |          |
      | IDC         | TestSystemUser | application/json |       |       | Get  | settings/credentials/SqlServer_Credentials |                                                                        | 200           |                  |          |
      | IDC         | TestSystemUser | application/json | raw   | false | Post | items/Default/root                         | ida/SqlServerPostprocessorPayloads_2019/SQLServerPP_BA_Tag.json        | 200           |                  |          |


     ########################################## Run the SqlServerDB Cataloger and PostProcessor Plugin #########################################


  @jdbc
  Scenario Outline: SC#1_3_Run the SqlServerDB Cataloger and PostProcessor Plugin
    Given endpoint for "<ServiceName>" for "<ServiceUser>" having "<Header>" and query param with "<Query>" "<Param>" for request type "<type>" with url "<url>" and body "<body>" and verify "<response code>" and "<response message>" using "<jsonPath>"
    Examples:
      | ServiceName | ServiceUser    | Header           | Query | Param | type         | url                                                                         | body                                                                  | response code | response message         | jsonPath                                                     |
      | IDC         | TestSystemUser | application/json | raw   | false | Put          | settings/analyzers/SQLServerDBDataSource                                    | ida/SqlServerPostprocessorPayloads_2019/SqlServer_DataSource_RDS.json | 204           |                          |                                                              |
      | IDC         | TestSystemUser | application/json | raw   | false | Get          | settings/analyzers/SQLServerDBDataSource                                    |                                                                       | 200           | SQLServer_DataSource_RDS |                                                              |
      | IDC         | TestSystemUser | application/json | raw   | false | Put          | settings/analyzers/SQLServerDBCataloger                                     | ida/SqlServerPostprocessorPayloads_2019/SqlServer_Cataloger_RDS.json  | 204           |                          |                                                              |
      | IDC         | TestSystemUser | application/json | raw   | false | Get          | settings/analyzers/SQLServerDBCataloger                                     |                                                                       | 200           | SQLServer_Cataloger_RDS  |                                                              |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/LocalNode/cataloger/SQLServerDBCataloger/*      |                                                                       | 200           | IDLE                     | $.[?(@.configurationName=='SQLServer_Cataloger_RDS')].status |
      | IDC         | TestSystemUser | application/json | raw   | false | Post         | extensions/analyzers/start/LocalNode/cataloger/SQLServerDBCataloger/*       | ida/SqlServerPostprocessorPayloads_2019/empty.json                    | 200           |                          |                                                              |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/LocalNode/cataloger/SQLServerDBCataloger/*      |                                                                       | 200           | RUNNING                  | $.[?(@.configurationName=='SQLServer_Cataloger_RDS')].status |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/LocalNode/cataloger/SQLServerDBCataloger/*      |                                                                       | 200           | IDLE                     | $.[?(@.configurationName=='SQLServer_Cataloger_RDS')].status |
      | IDC         | TestSystemUser | application/json | raw   | false | Put          | settings/analyzers/SQLServerDBPostProcessor                                 | ida/SqlServerPostprocessorPayloads_2019/SqlServer_Postprocessor.json  | 204           |                          |                                                              |
      | IDC         | TestSystemUser | application/json | raw   | false | Get          | settings/analyzers/SQLServerDBPostProcessor                                 |                                                                       | 200           | SQLServer_PostProcessor  |                                                              |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/InternalNode/lineage/SQLServerDBPostProcessor/* |                                                                       | 200           | IDLE                     | $.[?(@.configurationName=='SQLServer_PostProcessor')].status |
      | IDC         | TestSystemUser | application/json | raw   | false | Post         | extensions/analyzers/start/InternalNode/lineage/SQLServerDBPostProcessor/*  | ida/SqlServerPostprocessorPayloads_2019/empty.json                    | 200           |                          |                                                              |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/InternalNode/lineage/SQLServerDBPostProcessor/* |                                                                       | 200           | IDLE                     | $.[?(@.configurationName=='SQLServer_PostProcessor')].status |

     ########################################## Lineage Verification #########################################


   # 7193269 # 7193270 # 7193271 # 7193272 # 7193273 # 7193251 # 7193252 # 7193255 # 7193258 # 7193259 # 7193260 # 7193261 # 7193262 # 7193263 # 7193264 # 7193265 # 7193266 # 7193267 # 7193268 # 7193300 # 7193301 # 7193302  # 7193303 # 7193304 # 7193305 # 7193306 # 7193307 # 7193308  # 7193309 # 7193310 # 7193275
  Scenario Outline:SC#2_1_user retrieves ids for specific item name
    Given user connects "<database>" and run query using "<catalog>" with "<name>" and "<type>" and store the item id results in "<targetFile>"
    Examples:
      | database      | catalog | name                                                | type    | targetFile                                                                              |
      | APPDBPOSTGRES | Default | sqlserverviewtosingletable                          | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewtomultipletable                        | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | productmaterialview                                 | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | basecityview                                        | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewtoviewandviewtotable                   | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewtomultipletableinnerjoin               | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewtomultipletablewithjoindiffschema      | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewtomultipletablewithjoinhavingcondition | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewtomultipletablegroupbyhaving           | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewwithunion                              | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewwithunionall                           | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewleftouterjoin                          | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewrightouterjoin                         | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewfullouterjoin                          | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewfullcrossjoin                          | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewsubqueryusingwhere                     | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewsubqueryusingwhereexist                | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewfromcomplexstatement                   | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlservercitycomplexview                            | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | userdefinedtypetable1                               | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | testmultiplecolumnview                              | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | lineagetable2                                       | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | lineagetable56                                      | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | books                                               | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | category_staging                                    | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | lineagetable4                                       | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | lineagefunctiontable2                               | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | addresses                                           | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | lineageupdatetable2                                 | Table   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | trigger_vw_brands                                   | Trigger | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | trigger_product_audit                               | Trigger | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json |


     # 7193269 # 7193270 # 7193271 # 7193272 # 7193273 # 7193251 # 7193252 # 7193255 # 7193258 # 7193259 # 7193260 # 7193261 # 7193262 # 7193263 # 7193264 # 7193265 # 7193266 # 7193267 # 7193268 # 7193300 # 7193301 # 7193302  # 7193303 # 7193304 # 7193305 # 7193306 # 7193307 # 7193308  # 7193309 # 7193310 # 7193275
  Scenario Outline:SC#2_2_user copy the id to payload
    Given user copy the id from "<file>" to "<payloadFile>" with "<type>" using "<jsonPath>"
    Examples:
      | file                                                                                    | payloadFile                                                                                                                 | type    | jsonPath                                               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewto_singletable.json                         | Table   | $..sqlserverviewtosingletable                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewtomultipletable.json                        | Table   | $..sqlserverviewtomultipletable                        |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/productmaterialview.json                                 | Table   | $..productmaterialview                                 |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/basecityview.json                                        | Table   | $..basecityview                                        |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewtoviewandviewtotable.json                   | Table   | $..sqlserverviewtoviewandviewtotable                   |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewtomultipletableinnerjoin.json               | Table   | $..sqlserverviewtomultipletableinnerjoin               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewtomultipletablewithjoindiffschema.json      | Table   | $..sqlserverviewtomultipletablewithjoindiffschema      |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewtomultipletablewithjoinhavingcondition.json | Table   | $..sqlserverviewtomultipletablewithjoinhavingcondition |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewtomultipletablegroupbyhaving.json           | Table   | $..sqlserverviewtomultipletablegroupbyhaving           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewwithunion.json                              | Table   | $..sqlserverviewwithunion                              |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewwithunionall.json                           | Table   | $..sqlserverviewwithunionall                           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewleftouterjoin.json                          | Table   | $..sqlserverviewleftouterjoin                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewrightouterjoin.json                         | Table   | $..sqlserverviewrightouterjoin                         |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewfullouterjoin.json                          | Table   | $..sqlserverviewfullouterjoin                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewfullcrossjoin.json                          | Table   | $..sqlserverviewfullcrossjoin                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewsubqueryusingwhere.json                     | Table   | $..sqlserverviewsubqueryusingwhere                     |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewsubqueryusingwhereexist.json                | Table   | $..sqlserverviewsubqueryusingwhereexist                |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewfromcomplexstatement.json                   | Table   | $..sqlserverviewfromcomplexstatement                   |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlservercitycomplexview.json                            | Table   | $..sqlservercitycomplexview                            |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/userdefinedtypetable1.json                               | Table   | $..userdefinedtypetable1                               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/testmultiplecolumnview.json                              | Table   | $..testmultiplecolumnview                              |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/lineagetable2.json                                       | Table   | $..lineagetable2                                       |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/lineagetable56.json                                      | Table   | $..lineagetable56                                      |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/books.json                                               | Table   | $..books                                               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/category_staging.json                                    | Table   | $..category_staging                                    |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/lineagetable4.json                                       | Table   | $..lineagetable4                                       |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/lineagefunctiontable2.json                               | Table   | $..lineagefunctiontable2                               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/addresses.json                                           | Table   | $..addresses                                           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/lineageupdatetable2.json                                 | Table   | $..lineageupdatetable2                                 |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/trigger_vw_brands.json                                   | Trigger | $..trigger_vw_brands                                   |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/trigger_product_audit.json                               | Trigger | $..trigger_product_audit                               |


   # 7193269 # 7193270 # 7193271 # 7193272 # 7193273 # 7193251 # 7193252 # 7193255 # 7193258 # 7193259 # 7193260 # 7193261 # 7193262 # 7193263 # 7193264 # 7193265 # 7193266 # 7193267 # 7193268 # 7193300 # 7193301 # 7193302  # 7193303 # 7193304 # 7193305 # 7193306 # 7193307 # 7193308  # 7193309 # 7193310 # 7193275
  Scenario Outline:SC#2_3_user get the response of lineage edges and store the lineage values in file
    Given user hits "<request>" with "<url>" "<body>" for id from "<file>" "<type>" using "<path>" and verify "<statusCode>" and store response of "<jsonPath>" in "<targetFile>" for "<name>"
    Examples:
      | request | url                                                                   | body                                                                                                                        | file                                                                                    | type | path                                                   | statusCode | jsonPath   | targetFile                                                                                                                         | name                                                |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog,&exclude=MULTIHOP | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewto_singletable.json                         | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlserverviewtosingletable                          | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewto_singletable.json                         | sqlserverviewtosingletable                          |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewtomultipletable.json                        | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlserverviewtomultipletable                        | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtomultipletable.json                        | sqlserverviewtomultipletable                        |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/productmaterialview.json                                 | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..productmaterialview                                 | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/productmaterialview.json                                 | productmaterialview                                 |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/basecityview.json                                        | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..basecityview                                        | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/basecityview.json                                        | basecityview                                        |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewtoviewandviewtotable.json                   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlserverviewtoviewandviewtotable                   | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtoviewandviewtotable.json                   | sqlserverviewtoviewandviewtotable                   |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewtomultipletableinnerjoin.json               | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlserverviewtomultipletableinnerjoin               | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtomultipletableinnerjoin.json               | sqlserverviewtomultipletableinnerjoin               |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewtomultipletablewithjoindiffschema.json      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlserverviewtomultipletablewithjoindiffschema      | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtomultipletablewithjoindiffschema.json      | sqlserverviewtomultipletablewithjoindiffschema      |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewtomultipletablewithjoinhavingcondition.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlserverviewtomultipletablewithjoinhavingcondition | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtomultipletablewithjoinhavingcondition.json | sqlserverviewtomultipletablewithjoinhavingcondition |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog,&exclude=MULTIHOP | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewtomultipletablegroupbyhaving.json           | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlserverviewtomultipletablegroupbyhaving           | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtomultipletablegroupbyhaving.json           | sqlserverviewtomultipletablegroupbyhaving           |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewwithunion.json                              | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlserverviewwithunion                              | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewwithunion.json                              | sqlserverviewwithunion                              |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewwithunionall.json                           | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlserverviewwithunionall                           | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewwithunionall.json                           | sqlserverviewwithunionall                           |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewleftouterjoin.json                          | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlserverviewleftouterjoin                          | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewleftouterjoin.json                          | sqlserverviewleftouterjoin                          |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewrightouterjoin.json                         | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlserverviewrightouterjoin                         | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewrightouterjoin.json                         | sqlserverviewrightouterjoin                         |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewfullouterjoin.json                          | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlserverviewfullouterjoin                          | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewfullouterjoin.json                          | sqlserverviewfullouterjoin                          |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewfullcrossjoin.json                          | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlserverviewfullcrossjoin                          | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewfullcrossjoin.json                          | sqlserverviewfullcrossjoin                          |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewsubqueryusingwhere.json                     | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlserverviewsubqueryusingwhere                     | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewsubqueryusingwhere.json                     | sqlserverviewsubqueryusingwhere                     |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog,&exclude=MULTIHOP | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewsubqueryusingwhereexist.json                | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlserverviewsubqueryusingwhereexist                | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewsubqueryusingwhereexist.json                | sqlserverviewsubqueryusingwhereexist                |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlserverviewfromcomplexstatement.json                   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlserverviewfromcomplexstatement                   | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewfromcomplexstatement.json                   | sqlserverviewfromcomplexstatement                   |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/sqlservercitycomplexview.json                            | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..sqlservercitycomplexview                            | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlservercitycomplexview.json                            | sqlservercitycomplexview                            |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/userdefinedtypetable1.json                               | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..userdefinedtypetable1                               | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/userdefinedtypetable1.json                               | userdefinedtypetable1                               |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/testmultiplecolumnview.json                              | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..testmultiplecolumnview                              | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/testmultiplecolumnview.json                              | testmultiplecolumnview                              |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/lineagetable2.json                                       | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..lineagetable2                                       | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/lineagetable2.json                                       | lineagetable2                                       |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/lineagetable56.json                                      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..lineagetable56                                      | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/lineagetable56.json                                      | lineagetable56                                      |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/books.json                                               | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..books                                               | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/books.json                                               | books                                               |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog,&exclude=MULTIHOP | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/category_staging.json                                    | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..category_staging                                    | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/category_staging.json                                    | category_staging                                    |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/lineagetable4.json                                       | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..lineagetable4                                       | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/lineagetable4.json                                       | lineagetable4                                       |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/lineagefunctiontable2.json                               | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..lineagefunctiontable2                               | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/lineagefunctiontable2.json                               | lineagefunctiontable2                               |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/addresses.json                                           | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..addresses                                           | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/addresses.json                                           | addresses                                           |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/lineageupdatetable2.json                                 | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..lineageupdatetable2                                 | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/lineageupdatetable2.json                                 | lineageupdatetable2                                 |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/trigger_vw_brands.json                                   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..trigger_vw_brands                                   | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/trigger_vw_brands.json                                   | trigger_vw_brands                                   |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/payloads/trigger_product_audit.json                               | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/tableIDs.json | List | $..trigger_product_audit                               | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/trigger_product_audit.json                               | trigger_product_audit                               |


     # 7193269 # 7193270 # 7193271 # 7193272 # 7193273 # 7193251 # 7193252 # 7193255 # 7193258 # 7193259 # 7193260 # 7193261 # 7193262 # 7193263 # 7193264 # 7193265 # 7193266 # 7193267 # 7193268 # 7193300 # 7193301 # 7193302  # 7193303 # 7193304 # 7193305 # 7193306 # 7193307 # 7193308  # 7193309 # 7193310 # 7193275
  Scenario Outline:SC#2_4_user retrieve the name of id for each value stored in lineage data file
    Given user gets the name for each id stored in "<LineageFile>" under "<TableName>" and replace the id with name
    Examples:
      | LineageFile                                                                                                                        | TableName                                           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewto_singletable.json                         | sqlserverviewtosingletable                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtomultipletable.json                        | sqlserverviewtomultipletable                        |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/productmaterialview.json                                 | productmaterialview                                 |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/basecityview.json                                        | basecityview                                        |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtoviewandviewtotable.json                   | sqlserverviewtoviewandviewtotable                   |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtomultipletableinnerjoin.json               | sqlserverviewtomultipletableinnerjoin               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtomultipletablewithjoindiffschema.json      | sqlserverviewtomultipletablewithjoindiffschema      |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtomultipletablewithjoinhavingcondition.json | sqlserverviewtomultipletablewithjoinhavingcondition |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtomultipletablegroupbyhaving.json           | sqlserverviewtomultipletablegroupbyhaving           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewwithunion.json                              | sqlserverviewwithunion                              |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewwithunionall.json                           | sqlserverviewwithunionall                           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewleftouterjoin.json                          | sqlserverviewleftouterjoin                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewrightouterjoin.json                         | sqlserverviewrightouterjoin                         |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewfullouterjoin.json                          | sqlserverviewfullouterjoin                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewfullcrossjoin.json                          | sqlserverviewfullcrossjoin                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewsubqueryusingwhere.json                     | sqlserverviewsubqueryusingwhere                     |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewsubqueryusingwhereexist.json                | sqlserverviewsubqueryusingwhereexist                |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewfromcomplexstatement.json                   | sqlserverviewfromcomplexstatement                   |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlservercitycomplexview.json                            | sqlservercitycomplexview                            |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/userdefinedtypetable1.json                               | userdefinedtypetable1                               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/testmultiplecolumnview.json                              | testmultiplecolumnview                              |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/lineagetable2.json                                       | lineagetable2                                       |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/lineagetable56.json                                      | lineagetable56                                      |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/books.json                                               | books                                               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/category_staging.json                                    | category_staging                                    |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/lineagetable4.json                                       | lineagetable4                                       |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/lineagefunctiontable2.json                               | lineagefunctiontable2                               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/addresses.json                                           | addresses                                           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/lineageupdatetable2.json                                 | lineageupdatetable2                                 |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/trigger_vw_brands.json                                   | trigger_vw_brands                                   |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/trigger_product_audit.json                               | trigger_product_audit                               |


     # 7193269 # 7193270 # 7193271 # 7193272 # 7193273 # 7193251 # 7193252 # 7193255 # 7193258 # 7193259 # 7193260 # 7193261 # 7193262 # 7193263 # 7193264 # 7193265 # 7193266 # 7193267 # 7193268 # 7193300 # 7193301 # 7193302  # 7193303 # 7193304 # 7193305 # 7193306 # 7193307 # 7193308  # 7193309 # 7193310 # 7193275
  Scenario Outline:SC#2_5_user compares the expected lineage data and actual lineage data
    Given user json assert between "<expectedJson>" data and "<actualJson>" data
    Examples:
      | expectedJson                                                                                                                         | actualJson                                                                                                                         |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlserverviewto_singletable.json                         | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewto_singletable.json                         |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlserverviewtomultipletable.json                        | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtomultipletable.json                        |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/productmaterialview.json                                 | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/productmaterialview.json                                 |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/basecityview.json                                        | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/basecityview.json                                        |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlserverviewtoviewandviewtotable.json                   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtoviewandviewtotable.json                   |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlserverviewtomultipletableinnerjoin.json               | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtomultipletableinnerjoin.json               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlserverviewtomultipletablewithjoindiffschema.json      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtomultipletablewithjoindiffschema.json      |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlserverviewtomultipletablewithjoinhavingcondition.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtomultipletablewithjoinhavingcondition.json |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlserverviewtomultipletablegroupbyhaving.json           | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewtomultipletablegroupbyhaving.json           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlserverviewwithunion.json                              | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewwithunion.json                              |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlserverviewwithunionall.json                           | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewwithunionall.json                           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlserverviewleftouterjoin.json                          | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewleftouterjoin.json                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlserverviewrightouterjoin.json                         | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewrightouterjoin.json                         |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlserverviewfullouterjoin.json                          | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewfullouterjoin.json                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlserverviewfullcrossjoin.json                          | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewfullcrossjoin.json                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlserverviewsubqueryusingwhere.json                     | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewsubqueryusingwhere.json                     |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlserverviewsubqueryusingwhereexist.json                | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewsubqueryusingwhereexist.json                |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlserverviewfromcomplexstatement.json                   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlserverviewfromcomplexstatement.json                   |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/sqlservercitycomplexview.json                            | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/sqlservercitycomplexview.json                            |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/userdefinedtypetable1.json                               | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/userdefinedtypetable1.json                               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/testmultiplecolumnview.json                              | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/testmultiplecolumnview.json                              |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/lineagetable2.json                                       | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/lineagetable2.json                                       |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/lineagetable56.json                                      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/lineagetable56.json                                      |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/books.json                                               | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/books.json                                               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/category_staging.json                                    | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/category_staging.json                                    |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/lineagefunctiontable2.json                               | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/lineagefunctiontable2.json                               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/addresses.json                                           | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/addresses.json                                           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/lineageupdatetable2.json                                 | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/lineageupdatetable2.json                                 |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/trigger_vw_brands.json                                   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/trigger_vw_brands.json                                   |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/expectedJsonFiles/trigger_product_audit.json                               | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2019/actualJsonFiles/trigger_product_audit.json                               |


        # 7193274
  @webtest @positive
  Scenario:SC#3_1_Verify the  Processed Items and Logging enhancement of SqlServerDB Postprocessor Plugin
    Given User launch browser and traverse to login page
    And user enter credentials for "System Administrator1" role
    And user enters the search text "SQLServerPostProcessor" and clicks on search
    And user performs "facet selection" in "SQLServerPostProcessor" attribute under "Tags" facets in Item Search results page
    And user performs "facet selection" in "Analysis" attribute under "Metadata Type" facets in Item Search results page
    Then the following tags "SQL Server,SQLServerPostProcessor,SQL_Server_PP" should get displayed for the column "lineage/SQLServerDBPostProcessor/SQLServer_PostProcessor"
    And user performs "latest analysis click" in Item Results page for "lineage/SQLServerDBPostProcessor/SQLServer_PostProcessor%"
    Then the following metadata values should be displayed
      | metaDataAttribute         | metaDataValue | widgetName  |
      | Number of processed items | 2             | Description |
      | Number of errors          | 0             | Description |
    And user "verifies tab section values" has the following values in "Processed Items" Tab in Item View page
      | sqlserver.cshey0cobobn.us-east-1.rds.amazonaws.com |
      | sqlserver:1521                                     |
    Then Analysis log "lineage/SQLServerDBPostProcessor/SQLServer_PostProcessor%" should display below info/error/warning
      | type | logValue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | logCode       | pluginName               | removableText  |
      | INFO | Plugin started                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | ANALYSIS-0019 |                          |                |
      | INFO | Plugin Name:SQLServerDBPostProcessor, Plugin Type:lineage, Plugin Version:1.2.0.SNAPSHOT, Node Name:InternalNode, Host Name:330df03ec9c0, Plugin Configuration name:SQLServer_PostProcessor                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | ANALYSIS-0071 | SQLServerDBPostProcessor | Plugin Version |
      | INFO | Plugin SQLServerDBPostProcessor Configuration: --- 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: name: "SQLServer_PostProcessor" 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: pluginVersion: "LATEST" 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: label: 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: : "" 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: catalogName: "Default" 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: eventClass: null 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: eventCondition: null 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: nodeCondition: "name==\"InternalNode\"" 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: maxWorkSize: 100 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: tags: 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: - "SQLServerPostProcessor" 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: pluginType: "lineage" 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: dataSource: null 2020-10-22 06:50:42.100 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: credential: null 2020-10-22 06:50:42.100 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: businessApplicationName: "SQL_Server_PP" 2020-10-22 06:50:42.100 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: dryRun: false 2020-10-22 06:50:42.100 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: schedule: null 2020-10-22 06:50:42.100 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: filter: null 2020-10-22 06:50:42.100 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: pluginName: "SQLServerDBPostProcessor" 2020-10-22 06:50:42.100 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: arguments: [] 2020-10-22 06:50:42.100 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: type: "Lineage" | ANALYSIS-0073 | SQLServerDBPostProcessor |                |
      | INFO | Plugin SQLServerDBPostProcessor Start Time:2020-10-22 06:50:42.096, End Time:2020-10-22 06:50:44.692, Processed Count:2, Errors:0, Warnings:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | ANALYSIS-0072 | SQLServerDBPostProcessor |                |
      | INFO | Plugin completed processing (elapsed time in (HH:MM:SS.ms): 00:00:04.738)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | ANALYSIS-0020 |                          |                |


  # 7193274
  @positve @regression @sanity
  Scenario:SC#3_2_Delete cataloger and Analyzer analysis and tables
    And Delete multiple values in IDC UI with below parameters
      | deleteAction     | catalog | name                                               | type     | query | param |
      | SingleItemDelete | Default | sqlserver.cshey0cobobn.us-east-1.rds.amazonaws.com | Cluster  |       |       |
      | SingleItemDelete | Default | cataloger/SQLServerDBCataloger/%                   | Analysis |       |       |
      | SingleItemDelete | Default | lineage/SQLServerDBPostProcessor/%                 | Analysis |       |       |


  @webtest
  Scenario:SC#4_1_Verify the Dry run feature for the SqlServerDB Postprocessor
    Given user "update" the json file "ida/SqlServerPostprocessorPayloads_2019/SqlServer_Postprocessor_Dryrun.json" file for following values
      | jsonPath  | jsonValues | type    |
      | $..dryRun | true       | boolean |
    And Execute REST API with following parameters
      | Header           | Query | Param | type         | url                                                                         | body                                                                        | response code | response message | jsonPath                                                            |
      | application/json | raw   | false | Put          | settings/analyzers/SQLServerDBDataSource                                    | ida/SqlServerPostprocessorPayloads_2019/SqlServer_DataSource_RDS.json       | 204           |                  |                                                                     |
      |                  |       |       | Get          | settings/analyzers/SQLServerDBDataSource                                    |                                                                             | 200           | SQLServer_DataSource_RDS                 |                                             |
      |                  |       |       | Put          | settings/analyzers/SQLServerDBCataloger                                     | ida/SqlServerPostprocessorPayloads_2019/SqlServer_Cataloger_RDS.json        | 204           |                  |                                                                     |
      |                  |       |       | Get          | settings/analyzers/SQLServerDBCataloger                                     |                                                                             | 200           | SQLServer_Cataloger_RDS                 |                                              |
      |                  |       |       | RecursiveGet | extensions/analyzers/status/LocalNode/cataloger/SQLServerDBCataloger/*      |                                                                             | 200           | IDLE             | $.[?(@.configurationName=='SQLServer_Cataloger_RDS')].status        |
      |                  |       |       | Post         | extensions/analyzers/start/LocalNode/cataloger/SQLServerDBCataloger/*       | ida/SqlServerPostprocessorPayloads_2019/empty.json                          | 200           |                  |                                                                     |
      |                  |       |       | RecursiveGet | extensions/analyzers/status/LocalNode/cataloger/SQLServerDBCataloger/*      |                                                                             | 200           | IDLE             | $.[?(@.configurationName=='SQLServer_Cataloger_RDS')].status        |
      |                  |       |       | Put          | settings/analyzers/SQLServerDBPostProcessor                                 | ida/SqlServerPostprocessorPayloads_2019/SqlServer_Postprocessor_Dryrun.json | 204           |                  |                                                                     |
      |                  |       |       | Get          | settings/analyzers/SQLServerDBPostProcessor                                 |                                                                             | 200           | SQLServer_PostProcessor_DryRun                 |                                       |
      |                  |       |       | RecursiveGet | extensions/analyzers/status/InternalNode/lineage/SQLServerDBPostProcessor/* |                                                                             | 200           | IDLE             | $.[?(@.configurationName=='SQLServer_PostProcessor_DryRun')].status |
      |                  |       |       | Post         | extensions/analyzers/start/InternalNode/lineage/SQLServerDBPostProcessor/*  | ida/SqlServerPostprocessorPayloads_2019/empty.json                          | 200           |                  |                                                                     |
      |                  |       |       | RecursiveGet | extensions/analyzers/status/InternalNode/lineage/SQLServerDBPostProcessor/* |                                                                             | 200           | IDLE             | $.[?(@.configurationName=='SQLServer_PostProcessor_DryRun')].status |
    And User launch browser and traverse to login page
    And user enter credentials for "System Administrator1" role
    And user enters the search text "SQLServerPostProcessor" and clicks on search
    And user performs "facet selection" in "Analysis" attribute under "Metadata Type" facets in Item Search results page
    And user performs "latest analysis click" in Item Results page for "lineage/SQLServerDBPostProcessor/SQLServer_PostProcessor_DryRun%"
    Then the following metadata values should be displayed
      | metaDataAttribute         | metaDataValue | widgetName  |
      | Number of processed items | 0             | Description |
      | Number of errors          | 0             | Description |
    And user "widget not present" on "Processed Items" in Item view page
    Then user performs click and verify in new window
      | Table | value | Action               | RetainPrevwindow | indexSwitch |
      | Data  | log   | click and switch tab | No               |             |
    Then Analysis log "lineage/SQLServerDBPostProcessor/SQLServer_PostProcessor_DryRun%" should display below info/error/warning
      | type | logValue                                                                                            | logCode       | pluginName               | removableText |
      | INFO | Plugin SQLServerDBPostProcessor running on dry run mode                                             | ANALYSIS-0069 | SQLServerDBPostProcessor |               |
      | INFO | Plugin SQLServerDBPostProcessor processed 0 items on dry run mode and not written to the repository | ANALYSIS-0070 | SQLServerDBPostProcessor |               |
      | INFO | Plugin completed processing                                                                         | ANALYSIS-0020 |                          |               |


  @positve @regression @sanity
  Scenario:SC#4_2_Delete cataloger and Analyzer analysis and tables
    And Delete multiple values in IDC UI with below parameters
      | deleteAction     | catalog | name                                               | type                | query | param |
      | SingleItemDelete | Default | sqlserver.cshey0cobobn.us-east-1.rds.amazonaws.com | Cluster             |       |       |
      | SingleItemDelete | Default | cataloger/SQLServerDBCataloger/%                   | Analysis            |       |       |
      | SingleItemDelete | Default | lineage/SQLServerDBPostProcessor/%                 | Analysis            |       |       |
      | SingleItemDelete | Default | SQL_Server_PP                                      | BusinessApplication |       |       |


  @sanity @positive @regression
  Scenario Outline:SC#5_Delete Credentials,DataSource for SqlServerDB
    Given endpoint for "<ServiceName>" for "<ServiceUser>" having "<Header>" and query param with "<Query>" "<Param>" for request type "<type>" with url "<url>" and body "<body>" and verify "<response code>" and "<response message>" using "<jsonPath>"
    Examples:
      | ServiceName | ServiceUser    | Header           | Query | Param | type   | url                                         | body | response code | response message | jsonPath |
      | IDC         | TestSystemUser | application/json |       |       | Delete | settings/analyzers/SQLServerDBCataloger     |      | 204           |                  |          |
      | IDC         | TestSystemUser | application/json |       |       | Delete | settings/analyzers/SQLServerDBDataSource    |      | 204           |                  |          |
      | IDC         | TestSystemUser | application/json |       |       | Delete | settings/credentials/SqlServer_Credentials  |      | 200           |                  |          |
      | IDC         | TestSystemUser | application/json |       |       | Delete | settings/analyzers/SQLServerDBPostProcessor |      | 204           |                  |          |
