Feature: Verify the Lineage cases in API and UI for the SQLServer Postprocessor plugin for RDS


  @precondition
  Scenario: SC#1_Update credential payload json for SqlServerDB
    Given User update the below "RDS SqlServer Credentials readOnly" in following files using json path
      | filePath                                                               | username    | password    |
      | ida/SqlServerPostprocessorPayloads_2017/SqlServer_Credentials_RDS.json | $..userName | $..password |


##################### Add Credentials for SQlServer Postprocessor ####################################################


  @sanity @positive @regression @IDA_E2E
  Scenario Outline: SC#1_2_Add valid Credentials for SqlServerDB
    Given endpoint for "<ServiceName>" for "<ServiceUser>" having "<Header>" and query param with "<Query>" "<Param>" for request type "<type>" with url "<url>" and body "<body>" and verify "<response code>" and "<response message>" using "<jsonPath>"
    Examples:
      | ServiceName | ServiceUser    | Header           | Query | Param | type | url                                        | body                                                                   | response code | response message | jsonPath |
      | IDC         | TestSystemUser | application/json | raw   | false | Put  | settings/credentials/SqlServer_Credentials | ida/SqlServerPostprocessorPayloads_2017/SqlServer_Credentials_RDS.json | 200           |                  |          |
      | IDC         | TestSystemUser | application/json |       |       | Get  | settings/credentials/SqlServer_Credentials |                                                                        | 200           |                  |          |
      | IDC         | TestSystemUser | application/json | raw   | false | Post | items/Default/root                         | ida/SqlServerPostprocessorPayloads_2017/SQLServerPP_BA_Tag.json        | 200           |                  |          |


      ########################################## Run the SqlServerDB Cataloger and PostProcessor Plugin #########################################


  @jdbc
  Scenario Outline: SC#1_3_Run the SqlServerDB Cataloger and PostProcessor Plugin
    Given endpoint for "<ServiceName>" for "<ServiceUser>" having "<Header>" and query param with "<Query>" "<Param>" for request type "<type>" with url "<url>" and body "<body>" and verify "<response code>" and "<response message>" using "<jsonPath>"
    Examples:
      | ServiceName | ServiceUser    | Header           | Query | Param | type         | url                                                                         | body                                                                  | response code | response message         | jsonPath                                                     |
      | IDC         | TestSystemUser | application/json | raw   | false | Put          | settings/analyzers/SQLServerDBDataSource                                    | ida/SqlServerPostprocessorPayloads_2017/SqlServer_DataSource_RDS.json | 204           |                          |                                                              |
      | IDC         | TestSystemUser | application/json | raw   | false | Get          | settings/analyzers/SQLServerDBDataSource                                    |                                                                       | 200           | SQLServer_DataSource_RDS |                                                              |
      | IDC         | TestSystemUser | application/json | raw   | false | Put          | settings/analyzers/SQLServerDBCataloger                                     | ida/SqlServerPostprocessorPayloads_2017/SqlServer_Cataloger_RDS.json  | 204           |                          |                                                              |
      | IDC         | TestSystemUser | application/json | raw   | false | Get          | settings/analyzers/SQLServerDBCataloger                                     |                                                                       | 200           | SQLServer_Cataloger_RDS  |                                                              |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/LocalNode/cataloger/SQLServerDBCataloger/*      |                                                                       | 200           | IDLE                     | $.[?(@.configurationName=='SQLServer_Cataloger_RDS')].status |
      | IDC         | TestSystemUser | application/json | raw   | false | Post         | extensions/analyzers/start/LocalNode/cataloger/SQLServerDBCataloger/*       | ida/SqlServerPostprocessorPayloads_2017/empty.json                    | 200           |                          |                                                              |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/LocalNode/cataloger/SQLServerDBCataloger/*      |                                                                       | 200           | RUNNING                  | $.[?(@.configurationName=='SQLServer_Cataloger_RDS')].status |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/LocalNode/cataloger/SQLServerDBCataloger/*      |                                                                       | 200           | IDLE                     | $.[?(@.configurationName=='SQLServer_Cataloger_RDS')].status |
      | IDC         | TestSystemUser | application/json | raw   | false | Put          | settings/analyzers/SQLServerDBPostProcessor                                 | ida/SqlServerPostprocessorPayloads_2017/SqlServer_Postprocessor.json  | 204           |                          |                                                              |
      | IDC         | TestSystemUser | application/json | raw   | false | Get          | settings/analyzers/SQLServerDBPostProcessor                                 |                                                                       | 200           | SQLServer_PostProcessor  |                                                              |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/InternalNode/lineage/SQLServerDBPostProcessor/* |                                                                       | 200           | IDLE                     | $.[?(@.configurationName=='SQLServer_PostProcessor')].status |
      | IDC         | TestSystemUser | application/json | raw   | false | Post         | extensions/analyzers/start/InternalNode/lineage/SQLServerDBPostProcessor/*  | ida/SqlServerPostprocessorPayloads_2017/empty.json                    | 200           |                          |                                                              |
      | IDC         | TestSystemUser | application/json | raw   | false | RecursiveGet | extensions/analyzers/status/InternalNode/lineage/SQLServerDBPostProcessor/* |                                                                       | 200           | IDLE                     | $.[?(@.configurationName=='SQLServer_PostProcessor')].status |


       ########################################## Lineage Verification #########################################


   # 7193269 # 7193270 # 7193271 # 7193272 # 7193273 # 7193251 # 7193252 # 7193255 # 7193258 # 7193259 # 7193260 # 7193261 # 7193262 # 7193263 # 7193264 # 7193265 # 7193266 # 7193267 # 7193268 # 7193300 # 7193301 # 7193302  # 7193303 # 7193304 # 7193305 # 7193306 # 7193307 # 7193308  # 7193309 # 7193310 # 7193275
  Scenario Outline:SC#2_1_user retrieves ids for specific item name
    Given user connects "<database>" and run query using "<catalog>" with "<name>" and "<type>" and store the item id results in "<targetFile>"
    Examples:
      | database      | catalog | name                                                | type  | targetFile                                                                              |
      | APPDBPOSTGRES | Default | sqlserverviewtosingletable                          | Table | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewtomultipletable                        | Table | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | productmaterialview                                 | Table | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | basecityview                                        | Table | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewtoviewandviewtotable                   | Table | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewtomultipletableinnerjoin               | Table | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewtomultipletablewithjoindiffschema      | Table | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewtomultipletablewithjoinhavingcondition | Table | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewtomultipletablegroupbyhaving           | Table | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewwithunion                              | Table | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewwithunionall                           | Table | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewleftouterjoin                          | Table | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewrightouterjoin                         | Table | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewfullouterjoin                          | Table | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewfullcrossjoin                          | Table | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json |
      | APPDBPOSTGRES | Default | sqlserverviewsubqueryusingwhere                     | Table | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json |


     # 7193269 # 7193270 # 7193271 # 7193272 # 7193273 # 7193251 # 7193252 # 7193255 # 7193258 # 7193259 # 7193260 # 7193261 # 7193262 # 7193263 # 7193264 # 7193265 # 7193266 # 7193267 # 7193268 # 7193300 # 7193301 # 7193302  # 7193303 # 7193304 # 7193305 # 7193306 # 7193307 # 7193308  # 7193309 # 7193310 # 7193275
  Scenario Outline:SC#2_2_user copy the id to payload
    Given user copy the id from "<file>" to "<payloadFile>" with "<type>" using "<jsonPath>"
    Examples:
      | file                                                                                    | payloadFile                                                                                                                 | type  | jsonPath                                               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewto_singletable.json                         | Table | $..sqlserverviewtosingletable                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewtomultipletable.json                        | Table | $..sqlserverviewtomultipletable                        |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/productmaterialview.json                                 | Table | $..productmaterialview                                 |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/basecityview.json                                        | Table | $..basecityview                                        |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewtoviewandviewtotable.json                   | Table | $..sqlserverviewtoviewandviewtotable                   |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewtomultipletableinnerjoin.json               | Table | $..sqlserverviewtomultipletableinnerjoin               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewtomultipletablewithjoindiffschema.json      | Table | $..sqlserverviewtomultipletablewithjoindiffschema      |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewtomultipletablewithjoinhavingcondition.json | Table | $..sqlserverviewtomultipletablewithjoinhavingcondition |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewtomultipletablegroupbyhaving.json           | Table | $..sqlserverviewtomultipletablegroupbyhaving           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewwithunion.json                              | Table | $..sqlserverviewwithunion                              |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewwithunionall.json                           | Table | $..sqlserverviewwithunionall                           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewleftouterjoin.json                          | Table | $..sqlserverviewleftouterjoin                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewrightouterjoin.json                         | Table | $..sqlserverviewrightouterjoin                         |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewfullouterjoin.json                          | Table | $..sqlserverviewfullouterjoin                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewfullcrossjoin.json                          | Table | $..sqlserverviewfullcrossjoin                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewsubqueryusingwhere.json                     | Table | $..sqlserverviewsubqueryusingwhere                     |


   # 7193269 # 7193270 # 7193271 # 7193272 # 7193273 # 7193251 # 7193252 # 7193255 # 7193258 # 7193259 # 7193260 # 7193261 # 7193262 # 7193263 # 7193264 # 7193265 # 7193266 # 7193267 # 7193268 # 7193300 # 7193301 # 7193302  # 7193303 # 7193304 # 7193305 # 7193306 # 7193307 # 7193308  # 7193309 # 7193310 # 7193275
  Scenario Outline:SC#2_3_user get the response of lineage edges and store the lineage values in file
    Given user hits "<request>" with "<url>" "<body>" for id from "<file>" "<type>" using "<path>" and verify "<statusCode>" and store response of "<jsonPath>" in "<targetFile>" for "<name>"
    Examples:
      | request | url                                                                   | body                                                                                                                        | file                                                                                    | type | path                                                   | statusCode | jsonPath   | targetFile                                                                                                                         | name                                                |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog,&exclude=MULTIHOP | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewto_singletable.json                         | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | List | $..sqlserverviewtosingletable                          | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewto_singletable.json                         | sqlserverviewtosingletable                          |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewtomultipletable.json                        | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | List | $..sqlserverviewtomultipletable                        | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtomultipletable.json                        | sqlserverviewtomultipletable                        |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/productmaterialview.json                                 | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | List | $..productmaterialview                                 | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/productmaterialview.json                                 | productmaterialview                                 |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/basecityview.json                                        | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | List | $..basecityview                                        | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/basecityview.json                                        | basecityview                                        |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewtoviewandviewtotable.json                   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | List | $..sqlserverviewtoviewandviewtotable                   | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtoviewandviewtotable.json                   | sqlserverviewtoviewandviewtotable                   |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewtomultipletableinnerjoin.json               | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | List | $..sqlserverviewtomultipletableinnerjoin               | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtomultipletableinnerjoin.json               | sqlserverviewtomultipletableinnerjoin               |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewtomultipletablewithjoindiffschema.json      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | List | $..sqlserverviewtomultipletablewithjoindiffschema      | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtomultipletablewithjoindiffschema.json      | sqlserverviewtomultipletablewithjoindiffschema      |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewtomultipletablewithjoinhavingcondition.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | List | $..sqlserverviewtomultipletablewithjoinhavingcondition | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtomultipletablewithjoinhavingcondition.json | sqlserverviewtomultipletablewithjoinhavingcondition |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog,&exclude=MULTIHOP | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewtomultipletablegroupbyhaving.json           | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | List | $..sqlserverviewtomultipletablegroupbyhaving           | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtomultipletablegroupbyhaving.json           | sqlserverviewtomultipletablegroupbyhaving           |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewwithunion.json                              | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | List | $..sqlserverviewwithunion                              | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewwithunion.json                              | sqlserverviewwithunion                              |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewwithunionall.json                           | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | List | $..sqlserverviewwithunionall                           | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewwithunionall.json                           | sqlserverviewwithunionall                           |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewleftouterjoin.json                          | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | List | $..sqlserverviewleftouterjoin                          | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewleftouterjoin.json                          | sqlserverviewleftouterjoin                          |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewrightouterjoin.json                         | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | List | $..sqlserverviewrightouterjoin                         | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewrightouterjoin.json                         | sqlserverviewrightouterjoin                         |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewfullouterjoin.json                          | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | List | $..sqlserverviewfullouterjoin                          | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewfullouterjoin.json                          | sqlserverviewfullouterjoin                          |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewfullcrossjoin.json                          | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | List | $..sqlserverviewfullcrossjoin                          | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewfullcrossjoin.json                          | sqlserverviewfullcrossjoin                          |
      | Post    | lineages/Default?dir=BOTH&what=id,type,name,catalog&exclude=MULTIHOP  | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/payloads/sqlserverviewsubqueryusingwhere.json                     | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/tableIDs.json | List | $..sqlserverviewsubqueryusingwhere                     | 200        | $..edges.* | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewsubqueryusingwhere.json                     | sqlserverviewsubqueryusingwhere                     |


     # 7193269 # 7193270 # 7193271 # 7193272 # 7193273 # 7193251 # 7193252 # 7193255 # 7193258 # 7193259 # 7193260 # 7193261 # 7193262 # 7193263 # 7193264 # 7193265 # 7193266 # 7193267 # 7193268 # 7193300 # 7193301 # 7193302  # 7193303 # 7193304 # 7193305 # 7193306 # 7193307 # 7193308  # 7193309 # 7193310 # 7193275
  Scenario Outline:SC#2_4_user retrieve the name of id for each value stored in lineage data file
    Given user gets the name for each id stored in "<LineageFile>" under "<TableName>" and replace the id with name
    Examples:
      | LineageFile                                                                                                                        | TableName                                           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewto_singletable.json                         | sqlserverviewtosingletable                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtomultipletable.json                        | sqlserverviewtomultipletable                        |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/productmaterialview.json                                 | productmaterialview                                 |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/basecityview.json                                        | basecityview                                        |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtoviewandviewtotable.json                   | sqlserverviewtoviewandviewtotable                   |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtomultipletableinnerjoin.json               | sqlserverviewtomultipletableinnerjoin               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtomultipletablewithjoindiffschema.json      | sqlserverviewtomultipletablewithjoindiffschema      |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtomultipletablewithjoinhavingcondition.json | sqlserverviewtomultipletablewithjoinhavingcondition |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtomultipletablegroupbyhaving.json           | sqlserverviewtomultipletablegroupbyhaving           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewwithunion.json                              | sqlserverviewwithunion                              |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewwithunionall.json                           | sqlserverviewwithunionall                           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewleftouterjoin.json                          | sqlserverviewleftouterjoin                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewrightouterjoin.json                         | sqlserverviewrightouterjoin                         |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewfullouterjoin.json                          | sqlserverviewfullouterjoin                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewfullcrossjoin.json                          | sqlserverviewfullcrossjoin                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewsubqueryusingwhere.json                     | sqlserverviewsubqueryusingwhere                     |


     # 7193269 # 7193270 # 7193271 # 7193272 # 7193273 # 7193251 # 7193252 # 7193255 # 7193258 # 7193259 # 7193260 # 7193261 # 7193262 # 7193263 # 7193264 # 7193265 # 7193266 # 7193267 # 7193268 # 7193300 # 7193301 # 7193302  # 7193303 # 7193304 # 7193305 # 7193306 # 7193307 # 7193308  # 7193309 # 7193310 # 7193275
  Scenario Outline:SC#2_5_user compares the expected lineage data and actual lineage data
    Given user json assert between "<expectedJson>" data and "<actualJson>" data
    Examples:
      | expectedJson                                                                                                                         | actualJson                                                                                                                         |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/expectedJsonFiles/sqlserverviewto_singletable.json                         | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewto_singletable.json                         |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/expectedJsonFiles/sqlserverviewtomultipletable.json                        | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtomultipletable.json                        |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/expectedJsonFiles/productmaterialview.json                                 | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/productmaterialview.json                                 |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/expectedJsonFiles/basecityview.json                                        | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/basecityview.json                                        |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/expectedJsonFiles/sqlserverviewtoviewandviewtotable.json                   | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtoviewandviewtotable.json                   |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/expectedJsonFiles/sqlserverviewtomultipletableinnerjoin.json               | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtomultipletableinnerjoin.json               |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/expectedJsonFiles/sqlserverviewtomultipletablewithjoindiffschema.json      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtomultipletablewithjoindiffschema.json      |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/expectedJsonFiles/sqlserverviewtomultipletablewithjoinhavingcondition.json | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtomultipletablewithjoinhavingcondition.json |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/expectedJsonFiles/sqlserverviewtomultipletablegroupbyhaving.json           | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewtomultipletablegroupbyhaving.json           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/expectedJsonFiles/sqlserverviewwithunion.json                              | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewwithunion.json                              |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/expectedJsonFiles/sqlserverviewwithunionall.json                           | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewwithunionall.json                           |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/expectedJsonFiles/sqlserverviewleftouterjoin.json                          | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewleftouterjoin.json                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/expectedJsonFiles/sqlserverviewrightouterjoin.json                         | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewrightouterjoin.json                         |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/expectedJsonFiles/sqlserverviewfullouterjoin.json                          | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewfullouterjoin.json                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/expectedJsonFiles/sqlserverviewfullcrossjoin.json                          | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewfullcrossjoin.json                          |
      | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/expectedJsonFiles/sqlserverviewsubqueryusingwhere.json                     | Constant.REST_DIR/response/SqlServerPostprocessorRDS_2017/actualJsonFiles/sqlserverviewsubqueryusingwhere.json                     |


  # 7193274
  @webtest @positive
  Scenario:SC#3_1_Verify the  Processed Items and Logging enhancement of SqlServerDB Postprocessor Plugin
    Given User launch browser and traverse to login page
    And user enter credentials for "System Administrator1" role
    And user enters the search text "SQLServerPostProcessor" and clicks on search
    And user performs "facet selection" in "SQLServerPostProcessor" attribute under "Tags" facets in Item Search results page
    And user performs "facet selection" in "Analysis" attribute under "Metadata Type" facets in Item Search results page
    Then the following tags "SQL Server,SQLServerPostProcessor,SQL_Server_PP" should get displayed for the column "lineage/SQLServerDBPostProcessor/SQLServer_PostProcessor"
    And user performs "latest analysis click" in Item Results page for "lineage/SQLServerDBPostProcessor/SQLServer_PostProcessor%"
    Then the following metadata values should be displayed
      | metaDataAttribute         | metaDataValue | widgetName  |
      | Number of processed items | 2             | Description |
      | Number of errors          | 0             | Description |
    And user "verifies tab section values" has the following values in "Processed Items" Tab in Item View page
      | ddsqlserver.cshey0cobobn.us-east-1.rds.amazonaws.com |
      | sqlserver:1521                                       |
    Then Analysis log "lineage/SQLServerDBPostProcessor/SQLServer_PostProcessor%" should display below info/error/warning
      | type | logValue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | logCode       | pluginName               | removableText  |
      | INFO | Plugin started                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | ANALYSIS-0019 |                          |                |
      | INFO | Plugin Name:SQLServerDBPostProcessor, Plugin Type:lineage, Plugin Version:1.2.0.SNAPSHOT, Node Name:InternalNode, Host Name:330df03ec9c0, Plugin Configuration name:SQLServer_PostProcessor                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | ANALYSIS-0071 | SQLServerDBPostProcessor | Plugin Version |
      | INFO | Plugin SQLServerDBPostProcessor Configuration: --- 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: name: "SQLServer_PostProcessor" 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: pluginVersion: "LATEST" 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: label: 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: : "" 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: catalogName: "Default" 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: eventClass: null 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: eventCondition: null 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: nodeCondition: "name==\"InternalNode\"" 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: maxWorkSize: 100 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: tags: 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: - "SQLServerPostProcessor" 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: pluginType: "lineage" 2020-10-22 06:50:42.098 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: dataSource: null 2020-10-22 06:50:42.100 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: credential: null 2020-10-22 06:50:42.100 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: businessApplicationName: "SQL_Server_PP" 2020-10-22 06:50:42.100 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: dryRun: false 2020-10-22 06:50:42.100 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: schedule: null 2020-10-22 06:50:42.100 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: filter: null 2020-10-22 06:50:42.100 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: pluginName: "SQLServerDBPostProcessor" 2020-10-22 06:50:42.100 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: arguments: [] 2020-10-22 06:50:42.100 INFO - ANALYSIS-0073: Plugin SQLServerDBPostProcessor Configuration: type: "Lineage" | ANALYSIS-0073 | SQLServerDBPostProcessor |                |
      | INFO | Plugin SQLServerDBPostProcessor Start Time:2020-10-22 06:50:42.096, End Time:2020-10-22 06:50:44.692, Processed Count:2, Errors:0, Warnings:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | ANALYSIS-0072 | SQLServerDBPostProcessor |                |
      | INFO | Plugin completed (elapsed time in (HH:MM:SS.ms): 00:00:04.738)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | ANALYSIS-0020 |                          |                |


  @positve @regression @sanity
  Scenario:SC#3_2_Delete cataloger and Analyzer analysis and tables
    And Delete multiple values in IDC UI with below parameters
      | deleteAction     | catalog | name                                                 | type                | query | param |
      | SingleItemDelete | Default | ddsqlserver.cshey0cobobn.us-east-1.rds.amazonaws.com | Cluster             |       |       |
      | SingleItemDelete | Default | cataloger/SQLServerDBCataloger/%                     | Analysis            |       |       |
      | SingleItemDelete | Default | lineage/SQLServerDBPostProcessor/%                   | Analysis            |       |       |
      | SingleItemDelete | Default | SQL_Server_PP                                        | BusinessApplication |       |       |


  @sanity @positive @regression
  Scenario Outline:SC#4_Delete Credentials,DataSource for SqlServerDB
    Given endpoint for "<ServiceName>" for "<ServiceUser>" having "<Header>" and query param with "<Query>" "<Param>" for request type "<type>" with url "<url>" and body "<body>" and verify "<response code>" and "<response message>" using "<jsonPath>"
    Examples:
      | ServiceName | ServiceUser    | Header           | Query | Param | type   | url                                         | body | response code | response message | jsonPath |
      | IDC         | TestSystemUser | application/json |       |       | Delete | settings/analyzers/SQLServerDBCataloger     |      | 204           |                  |          |
      | IDC         | TestSystemUser | application/json |       |       | Delete | settings/analyzers/SQLServerDBDataSource    |      | 204           |                  |          |
      | IDC         | TestSystemUser | application/json |       |       | Delete | settings/analyzers/SQLServerDBPostProcessor |      | 204           |                  |          |
      | IDC         | TestSystemUser | application/json |       |       | Delete | settings/credentials/SqlServer_Credentials  |      | 200           |                  |          |