Feature: MLP-21661: To validate the End to End Lineage of itmes cataloged by SnowflakeDB cataloger using SnowflakePostProcessor

  # 7059021 # 7059000 # 7059022 # 7059027 # 7059045 # 7059029 # 7059032 # 7059031 # 7059023 # 7059034
  # 7059020 # 7059019 # 7059046 # 7059015 # 7058997 # 7063172 # 7059036 # 7059038 # 7063767 # 7059004

  @MLP-21661 @sanity @positive @regression
  Scenario Outline:SC#1: Add valid Credentials for Snowflake DB
    Given endpoint for "<ServiceName>" for "<ServiceUser>" having "<Header>" and query param with "<Query>" "<Param>" for request type "<type>" with url "<url>" and body "<body>" and verify "<response code>" and "<response message>" using "<jsonPath>"
    Examples:
      | ServiceName | ServiceUser    | Header           | Query | Param | type | url                                                    | body                                                                           | response code | response message | jsonPath |
      | IDC         | TestSystemUser | application/json |       |       | Put  | settings/credentials/SnowflakeCredentialsPostprocessor | ida/snowflakePayloads/SwnowflakePostprocessorConfigs/SnowflakeCredentials.json | 200           |                  |          |
      | IDC         | TestSystemUser | application/json |       |       | Get  | settings/credentials/SnowflakeCredentialsPostprocessor |                                                                                | 200           |                  |          |
      | IDC         | TestSystemUser | application/json |       |       | Put  | settings/analyzers/SnowflakeDBDataSource               | ida/snowflakePayloads/SwnowflakePostprocessorConfigs/SnowflakeDatasource.json  | 204           |                  |          |
      | IDC         | TestSystemUser | application/json |       |       | Get  | settings/analyzers/SnowflakeDBDataSource               |                                                                                | 200           |                  |          |


  @MLP-21661 @sanity @positive @regression @snowflake
  Scenario Outline:SC#1: Create snowflakeDB Cataloger and SnowflakePostProcessor Plugin configuration and run.
    Given endpoint for "<ServiceName>" for "<ServiceUser>" having "<Header>" and query param with "<Query>" "<Param>" for request type "<type>" with url "<url>" and body "<body>" and verify "<response code>" and "<response message>" using "<jsonPath>"
    Examples:
      | ServiceName | ServiceUser    | Header           | Query | Param | type         | url                                                                                              | body                                                                             | response code | response message        | jsonPath                                                     |
      | IDC         | TestSystemUser | application/json |       |       | Put          | settings/license                                                                                 | ida\hbasePayloads\DataSource\license_DS.json                                     | 204           |                         |                                                              |
      | IDC         | TestSystemUser | application/json |       |       | Put          | settings/analyzers/SnowflakeDBCataloger                                                          | ida/snowflakePayloads/SwnowflakePostprocessorConfigs/SnowflakeCataloger.json     | 204           |                         |                                                              |
      | IDC         | TestSystemUser | application/json |       |       | Get          | settings/analyzers/SnowflakeDBCataloger                                                          |                                                                                  | 200           | SnowflakeDBCataloger_PP |                                                              |
      | IDC         | TestSystemUser | application/json |       |       | RecursiveGet | extensions/analyzers/status/LocalNode/cataloger/SnowflakeDBCataloger/SnowflakeDBCataloger_PP        |                                                                                  | 200           | IDLE                    | $.[?(@.configurationName=='SnowflakeDBCataloger_PP')].status |
      | IDC         | TestSystemUser | application/json |       |       | Post         | extensions/analyzers/start/LocalNode/cataloger/SnowflakeDBCataloger/SnowflakeDBCataloger_PP         |                                                                                  | 200           |                         |                                                              |
      | IDC         | TestSystemUser | application/json |       |       | RecursiveGet | extensions/analyzers/status/LocalNode/cataloger/SnowflakeDBCataloger/SnowflakeDBCataloger_PP        |                                                                                  | 200           | IDLE                    | $.[?(@.configurationName=='SnowflakeDBCataloger_PP')].status |
      | IDC         | TestSystemUser | application/json |       |       | Put          | settings/analyzers/SnowflakeDBPostProcessor                                                      | ida/snowflakePayloads/SwnowflakePostprocessorConfigs/SnowflakePostprocessor.json | 204           |                         |                                                              |
      | IDC         | TestSystemUser | application/json |       |       | Get          | settings/analyzers/SnowflakeDBPostProcessor                                                      |                                                                                  | 200           | SnowflakePostProcessor  |                                                              |
      | IDC         | TestSystemUser | application/json |       |       | RecursiveGet | extensions/analyzers/status/InternalNode/lineage/SnowflakeDBPostProcessor/SnowflakePostProcessor |                                                                                  | 200           | IDLE                    | $.[?(@.configurationName=='SnowflakePostProcessor')].status  |
      | IDC         | TestSystemUser | application/json |       |       | Post         | extensions/analyzers/start/InternalNode/lineage/SnowflakeDBPostProcessor/SnowflakePostProcessor  |                                                                                  | 200           |                         |                                                              |
      | IDC         | TestSystemUser | application/json |       |       | RecursiveGet | extensions/analyzers/status/InternalNode/lineage/SnowflakeDBPostProcessor/SnowflakePostProcessor |                                                                                  | 200           | IDLE                    | $.[?(@.configurationName=='SnowflakePostProcessor')].status  |


  @MLP-21661 @sanity @positive @regression @snowflake
  Scenario: SC#1: user get all lineage hops id,s and get the source target value from database
    Given user retrieves all lineage hops values for below parameters
      | database      | retrive              | catalog | type  | lineageFlow  | name                                           | asg_scopeid | targetFile                                               | jsonpath |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | Snowviewtosingletable                          |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | Snowviewtomultipletable                        |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | Snowsingletablespecificcolumns                 |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | Snowmultipletablespecificcolumns               |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowSingleViewtoView                           |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewfromViewToViewViewToTable              |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewfromMultipleExternalTables             |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewfromExternalTableView                  |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewfromMultipleExternalTablesView         |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewToMultipleTableWithJoin                |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewToMultipleTableWithJoinDiffSchema      |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewToMultipleTableWithJoinhavingCondition |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewToMultipleTableGroupbyHaving           |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewWithUnion                              |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewWithUnionAll                           |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewInnerjoin                              |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewLeftOuterjoin                          |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewRightOuterjoin                         |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewFullOuterjoin                          |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewFullCrossjoin                          |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewNaturaljoin                            |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewSubqueryUsingWhere                     |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewSubqueryUsingWhereExist                |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | SnowViewFromComplexStatement                   |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | Snowcityview                                   |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
      | APPDBPOSTGRES | bulkFunctionHopNames | Default | Table | Table-->hops | Snowcitycomplexview                            |             | response/SnowflakePostProcessor/Lineage/bulkLineage.json |          |
    And user hits the following API with given parameters and store the api response in file
      | ServiceName | ServiceUser    | Header           | Query | Param | type | url                                                 | bodyFile                                                 | path                                                             | response code | response message | jsonPath | targetFile                                                     |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.Snowviewtosingletable                          | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.Snowviewtomultipletable                        | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.Snowsingletablespecificcolumns                 | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.Snowmultipletablespecificcolumns               | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowSingleViewtoView                           | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewfromViewToViewViewToTable              | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewfromMultipleExternalTables             | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewfromExternalTableView                  | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewfromMultipleExternalTablesView         | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewToMultipleTableWithJoin                | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewToMultipleTableWithJoinDiffSchema      | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewToMultipleTableWithJoinhavingCondition | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewToMultipleTableGroupbyHaving           | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewWithUnion                              | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewWithUnionAll                           | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewInnerjoin                              | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewLeftOuterjoin                          | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewRightOuterjoin                         | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewFullOuterjoin                          | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewFullCrossjoin                          | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewNaturaljoin                            | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewSubqueryUsingWhere                     | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewSubqueryUsingWhereExist                | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.Snowcityview                                   | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.Snowcitycomplexview                            | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
      | IDC         | TestSystemUser | application/json |       |       | Post | lineages/Default?dir=BOTH&what=id,type,name,catalog | response/SnowflakePostProcessor/Lineage/bulkLineage.json | $.lineagePayLoads.SnowViewFromComplexStatement                   | 200           |                  | edges    | response/SnowflakePostProcessor/Lineage/actualLineagehops.json |
    And user retrieves the name of each id stored in files with below parameters
      | fileName                                                                         | JsonPath                                       |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | Snowviewtosingletable                          |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | Snowviewtomultipletable                        |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | Snowsingletablespecificcolumns                 |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | Snowmultipletablespecificcolumns               |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowSingleViewtoView                           |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewfromViewToViewViewToTable              |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewfromMultipleExternalTables             |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewfromExternalTableView                  |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewfromMultipleExternalTablesView         |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewToMultipleTableWithJoin                |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewToMultipleTableWithJoinDiffSchema      |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewToMultipleTableWithJoinhavingCondition |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewToMultipleTableGroupbyHaving           |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewWithUnion                              |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewWithUnionAll                           |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewInnerjoin                              |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewLeftOuterjoin                          |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewRightOuterjoin                         |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewFullOuterjoin                          |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewFullCrossjoin                          |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewNaturaljoin                            |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewSubqueryUsingWhere                     |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewSubqueryUsingWhereExist                |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | Snowcityview                                   |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | Snowcitycomplexview                            |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | SnowViewFromComplexStatement                   |

  @MLP-21661 @sanity @positive @regression @snowflake
  Scenario Outline: SC#1 user compares the expected lineage data and actual lineage data
    Given user json assert between "<expectedJson>" data and "<actualJson>" data
    Examples:
      | expectedJson                                                                     | actualJson                                                                         |
      | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/actualLineagehops.json | Constant.REST_DIR/response/SnowflakePostProcessor/Lineage/expectedLineagehops.json |

  @MLP-21661 @sanity @positive @regression @snowflake
  Scenario:SC#1_Delete Cluster , Cataloger and Analyzer Analysis file
    Given Delete multiple values in IDC UI with below parameters
      | deleteAction     | catalog | name                                                     | type     | query | param |
      | MultipleIDDelete | Default | asg_partner.us-east-1.snowflakecomputing.com             | Cluster  |       |       |
      | MultipleIDDelete | Default | cataloger/SnowflakeDBCataloger/SnowflakeDBCataloger%     | Analysis |       |       |
      | MultipleIDDelete | Default | lineage/SnowflakeDBPostProcessor/SnowflakePostProcessor% | Analysis |       |       |

  @MLP-21661 @sanity @positive @regression @snowflake
  Scenario Outline: Delete Credentials, Datasource ,cataloger and Postprocessor config for SnowflakeDBCataloger
    Given endpoint for "<ServiceName>" for "<ServiceUser>" having "<Header>" and query param with "<Query>" "<Param>" for request type "<type>" with url "<url>" and body "<body>" and verify "<response code>" and "<response message>" using "<jsonPath>"
    Examples:
      | ServiceName | ServiceUser    | Header           | Query | Param | type   | url                                                                       | body | response code | response message | jsonPath |
      | IDC         | TestSystemUser | application/json |       |       | Delete | settings/analyzers/SnowflakeDBCataloger/SnowflakeDBCataloger_PP           |      | 204           |                  |          |
      | IDC         | TestSystemUser | application/json |       |       | Delete | settings/analyzers/SnowflakeDBDataSource/SnowflakeDataSourcePostprocessor |      | 204           |                  |          |
      | IDC         | TestSystemUser | application/json |       |       | Delete | settings/analyzers/SnowflakeDBPostProcessor                               |      | 204           |                  |          |
      | IDC         | TestSystemUser | application/json |       |       | Delete | settings/credentials/SnowflakeCredentialsPostprocessor                    |      | 200           |                  |          |
