Feature: Feature to validate Plugin Metadata within a plugin

  @webtest @4239 @sanity @positive @regression

  Scenario: Verify plugin metadata attributes appearing for different plugins in IDC UI and the attributes in schema file (.json) matches
    Given User launch browser and traverse to login page
    And user enter credentials for "System Administrator" role
    And user clicks on Administration widget
    And user clicks on Bundle Manager link in administration tab
    And user clicks on bundle name "Analysis"
    And user validate the bundle information for parameters
      | SubBundleName                                 | BundleVersion | pluginName                     | Description                                                            | Supported extensions | Supported content              | Supported technologies           | IDA Node restrictions: | Type of analyzer | analysis.itemtypes                                                                                                                                                                                                                                                        |
      | com.asg.dis.adu.EDIBus                        |               | EDIBus                         | Transfers data between CoreDI and new DI                               |                      |                                |                                  | internal               | bulk             |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.AmazonRedshift           |               | AmazonRedshiftCataloger        | Redshift Cataloger                                                     |                      |                                | Cloud Data, Redshift             |                        | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.AmazonRedshift           |               | AmazonRedshiftAnalyzer         | Redshift Analyzer                                                      |                      |                                | Cloud Data, Redshift             |                        | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.AmazonS3                 |               | AmazonS3Cataloger              | Amazon S3 Cataloger                                                    |                      |                                | Cloud Data, Amazon S3            |                        | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Antlr                    |               | AntlrParser                    | Use Antlr to parse sources                                             |                      |                                | Programming, Generic             |                        | parser           |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.AvroS3                   |               | AvroS3Cataloger                | Avro S3 Cataloger                                                      |                      |                                | Data Files, Avro                 |                        | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.AzureCosmosDatabase      |               | AzureCosmosCataloger           | Azure Cosmos Cataloger                                                 |                      |                                | Cloud Data, Azure Cosmos         |                        | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.AzureSQLDatabase         |               | AzureSQLDatabaseCataloger      | Azure SQL Database Cataloger                                           |                      |                                | Cloud Data, Azure SQL DB         |                        | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.AzureSQLDataWarehouse    |               | AzureSQLDataWarehouseCataloger | Azure SQL Data Warehouse Cataloger                                     |                      |                                | Cloud Data, Azure SQL DW         |                        | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Cassandra                |               | CassandraCataloger             | Cassandra Cataloger                                                    |                      |                                | NoSQL Databases, Cassandra       |                        | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Cdap                     |               | CdapCataloger                  | Retrieves Cdap metadata                                                |                      |                                | Big Data, CDAP                   |                        | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Cdap                     |               | CdapAnalyzer                   | Analyze Cdap data                                                      |                      |                                | Big Data, CDAP                   |                        | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.CNavigator               |               | CNavigatorCataloger            | Retrieves metadata and lineage information from Cloudera Navigator API |                      |                                | Big Data, Cloudera Navigator     |                        | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Gemfire                  |               | GemfireCataloger               | This plugin catalogs the data from Gemfire                             |                      |                                | In-Memory Databases, Gemfire     |                        | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Git                      |               | GitCollector                   | Collect sources from Git                                               |                      |                                | Source Control, Git              |                        | collector        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.LocalFileCollector       |               | LocalFileCollector             | Collect sources from a local folder                                    |                      |                                | Data Files, Local Files          |                        | collector        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Mobius                   |               | MobiusAnalyzer                 | Analyzes Mobius documents                                              |                      |                                | Data Archives, Mobius            |                        | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Mobius                   |               | MobiusCataloger                | Retrieves Mobius metadata                                              |                      |                                | Data Archives, Mobius            |                        | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.MongoDB                  |               | MongoDBCataloger               | MongoDB Cataloger                                                      |                      |                                | NoSQL Databases, MongoDB         |                        | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Neo4j                    |               | Neo4jCataloger                 | This is a neo4j cataloger to catalog the data                          |                      |                                | Graph Databases, Neo4j           |                        | cataloger        | analysis.itemtypes: Cluster, Service, Host, Database, Table, Column, Relationship, Field                                                                                                                                                                                  |
      | com.asg.dis.analysis.Oracle-JDBC              |               | OracleDBCataloger              | Oracle Cataloger                                                       |                      |                                | Relational Databases, Oracle     |                        | cataloger        | Cluster, Service, Database, User, Schema, Table, Column, Constraint, Index, Routine, DataField, DataCluster, IndexExtension, Component, Content, File, DatabaseLink, RoutinePackage, Sequence, Synonym, Tablespace, UserRole, Configuration, DataType, Partition, Trigger |
      | com.asg.dis.analysis.Oracle-JDBC              |               | OracleDBAnalyzer               | JDBC Analyzer                                                          | sql                  |                                | Relational Databases, Oracle     |                        | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Oracle-JDBC              |               | OracleDBPostProcessor          | Oracle Post Processor                                                  |                      |                                |                                  | internal               | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Postgres-JDBC            |               | PostgresJDBCCataloger          | JDBC Cataloger                                                         |                      |                                | Relational Databases, PostgreSQL |                        | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Postgres-JDBC            |               | PostgresJDBCAnalyzer           | JDBC Analyzer                                                          | sql                  |                                | Relational Databases, PostgreSQL |                        | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Python                   |               | PythonSparkLineage             | Python Spark Lineage                                                   |                      |                                | Programming, Spark               |                        | lineage          |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Python                   |               | PythonImportLinker             | Python Linker resolving imports                                        |                      | text/x-python                  | Programming, Python              |                        | linker           |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Python                   |               | PythonUseFunctionLinker        | Python Linker between functions                                        |                      | text/x-python                  | Programming, Python              |                        | linker           |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Python                   |               | PythonPackageLinker            | Python Linker between packages                                         |                      | text/x-python                  | Programming, Python              |                        | linker           |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Python                   |               | PythonParser                   | Python Parser                                                          |                      | text/x-python                  | Programming, Python              |                        | parser           |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.Snowflake                |               | SnowflakeJDBCCataloger         | Snowflake Cataloger                                                    |                      |                                | Cloud Data, Snowflake            |                        | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.SQLPostProcessor         |               | SQLPostProcessor               | SQL Post Processor                                                     |                      |                                |                                  | internal               | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.UDB                      |               | UDBCataloger                   | UDB Cataloger                                                          |                      |                                | Relational Databases, DB2        |                        | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.UDB                      |               | UDBAnalyzer                    | UDB JDBC Analyzer                                                      | sql                  |                                | Relational Databases, DB2        |                        | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.TeraData-JDBC            |               | TeradataAnalyzer               | JDBC Analyzer                                                          | sql                  | Relational Databases, Teradata |                                  |                        | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.analysis.TeraData-JDBC            |               | TeradataCataloger              | Teradata Cataloger                                                     |                      | Relational Databases, Teradata |                                  |                        | cataloger        | Cluster, Service, Database, User, Table, Column, Constraint, Index, Routine                                                                                                                                                                                               |
      | com.asg.dis.analysis.UnstructuredDataAnalyzer |               | UnstructuredDataAnalyzer       | Unstructured Data Analyzer                                             |                      |                                | Content, Unstructured            |                        | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.ingestion.AmbariResolver          |               | AmbariResolver                 | Retrieves cluster name from Ambari                                     |                      |                                | Big Data, Ambari                 | bigdata                | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.ingestion.AvroAnalyzer            |               | AvroAnalyzer                   | Calculates statistics and does pattern matching                        |                      |                                | Data Files, Avro                 | bigdata                | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.ingestion.BigDataAnalyzer         |               | BigDataAnalyzer                | Calculates statistics and does pattern matching                        |                      |                                | Big Data, Hive, Hadoop Files     | bigdata                | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.ingestion.HBase                   |               | HBaseAnalyzer                  | Retrieves metadata information from HBase using HBase Rest API         |                      |                                | Big Data, HBase                  |                        | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.ingestion.HBase                   |               | HBaseCataloger                 | Retrieves metadata information from HBase using HBase Rest API         |                      |                                | Big Data, HBase                  |                        | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.ingestion.Hdfs                    |               | HdfsMonitor                    | Monitors HDFS for changes in files and directories                     |                      |                                | Big Data, Hadoop Files           | bigdata                | monitor          |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.ingestion.Hdfs                    |               | BigDataAnalyzer                | Calculates statistics and does pattern matching                        |                      |                                | Big Data, Hive, Hadoop Files     | bigdata                | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.ingestion.Hdfs                    |               | HdfsCataloger                  | Retrieves HDFS metadata                                                |                      |                                | Big Data, Hadoop Files           | bigdata                | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.ingestion.Hive                    |               | HiveCataloger                  | Retrieves Hive metadata                                                |                      |                                | Big Data, Hive                   | bigdata                | cataloger        |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.ingestion.Hive                    |               | HiveMonitor                    | Monitors Hive for changes in tables                                    |                      |                                | Big Data, Hive                   | bigdata                | monitor          |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.ingestion.Hive                    |               | BigDataAnalyzer                | Calculates statistics and does pattern matching                        |                      |                                | Big Data, Hive, Hadoop Files     | bigdata                | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.ingestion.Hive                    |               | HiveQueryParser                | Parses Hive queries                                                    |                      |                                | Big Data, Hive                   | bigdata                | parser           |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.ingestion.MLAnalyzer              |               | MLAnalyzer                     | Performs automatic tagging via data similarity                         |                      |                                | Big Data, Hive, Hadoop Files     | bigdata                | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.ingestion.ParquetAnalyzer         |               | ParquetAnalyzer                | Calculates statistics and does pattern matching                        |                      |                                | Big Data, Parquet, Hadoop Files  | bigdata                | dataanalyzer     |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.ingestion.UploadHive              |               | UploadHive                     | Uploads Excel data to Hive tables                                      |                      |                                | Big Data, Hive                   | bigdata                | uploader         |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.platform.CatalogLinker            |               | HiveDirectoryLinker            | links Hive tables and HDFS directories that contain them               |                      |                                | Big Data, Hive, Hadoop Files     |                        | linker           |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.platform.CatalogLinker            |               | CommonLineage                  | Calculate lineage generically on ASTM tree                             |                      |                                | Programming, Generic             |                        | lineage          |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.platform.CatalogLinker            |               | CommonLinker                   | Calculate links generically on ASTM tree                               |                      |                                | Programming, Generic             |                        | linker           |                                                                                                                                                                                                                                                                           |
      | com.asg.dis.platform.SimilarityLinker         |               | SimilarityLinker               | Generic similarity detector                                            |                      |                                |                                  |                        | linker           |                                                                                                                                                                                                                                                                           |






#
#  Scenario Outline: Verify plugin metadata attributes appearing for different plugins in IDC UI and the attributes in schema file (.json) matches
#  @webtest @4239 @sanity @positive @regression
#    Given User launch browser and traverse to login page
#    And user enter credentials for "System Administrator" role
#    And user clicks on Administration widget
#    And user clicks on Bundle Manager link in administration tab
#    And user clicks on bundle name "Analysis"
#    And user clicks on sub bundle name "<SubBundleName>"
#    And user clicks on bundle version
#    And user clicks on plugin name "<pluginName>"
#  Then verify the metadata of the plugin "<pluginName>"
#      | Description           | <Description>           |
#      | SupportedTechnologies | <SupportedTechnologies> |
#      | TypeofAnalyzer        | <TypeofAnalyzer>        |
#      | SupportedContentTypes | <SupportedContentTypes> |
#      | SupportedExtentions   | <SupportedExtentions>   |
#      | IDANoderestrictions   | <IDANoderestrictions>   |
#    Then user validates the database for "<pluginName>" has following tags in postgres
#      | DBDescription           | <DBDescription>           |
#      | DBSupportedTechnologies | <DBSupportedTechnologies> |
#      | DBTypeofAnalyzer        | <DBTypeofAnalyzer>        |
#      | DBContentTypes          | <DBContentTypes>          |
#      | DBSupportedExtentions   | <DBSupportedExtentions>   |
#      | DBIDANoderestrictions   | <DBIDANoderestrictions>   |
#    And sync the test execution for "5" seconds
#
#    Examples:
#      | SubBundleName                                 | pluginName                     | Description                                                                         | SupportedTechnologies                                     | TypeofAnalyzer                 | IDANoderestrictions                     | DBDescription                                                                               | DBSupportedTechnologies                                         | DBTypeofAnalyzer               | SupportedContentTypes                  | DBContentTypes                            | SupportedExtentions       | DBSupportedExtentions | DBIDANoderestrictions                       |
#      | com.asg.dis.ingestion.BigDataAnalyzer         | BigDataAnalyzer                | Description: Calculates statistics and does pattern matching                        | Supported technologies: Big Data, Hive, Hadoop Files      | Type of analyzer: dataanalyzer | IDA Node restrictions: type=='bigdata'  | "description":{"":"Calculates statistics and does pattern matching"}                        | "analysis.technologies":["Big Data",["Hive","Hadoop Files"]]    | "analysis.type":"dataanalyzer" |                                        |                                           |                           |                       | "analysis.nodeCondition":"type=='bigdata'"  |
#      | com.asg.dis.analysis.Antlr                    | AntlrParser                    | Description: Use Antlr to parse sources                                             | Supported technologies: Programming, Generic              | Type of analyzer: parser       |                                         | "description":{"":"Use Antlr to parse sources"}                                             | "analysis.technologies":["Programming","Generic"]               | "analysis.type":"parser"       |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.UnstructuredDataAnalyzer | UnstructuredDataAnalyzer       | Description: Unstructured Data Analyzer                                             | Supported technologies: Content, UnstructuredDataAnalyzer | Type of analyzer: dataanalyzer |                                         | "description":{"":"Unstructured Data Analyzer"}                                             | "analysis.technologies":["Content","UnstructuredDataAnalyzer"]  | "analysis.type":"dataanalyzer" |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.ingestion.MLAnalyzer              | MLAnalyzer                     | Description: Performs automatic tagging via data similarity                         | Supported technologies: Big Data, Hive, Hadoop Files      | Type of analyzer: dataanalyzer | IDA Node restrictions: type=='bigdata'  | "description":{"":"Performs automatic tagging via data similarity"}                         | "analysis.technologies":["Big Data",["Hive","Hadoop Files"]]    | "analysis.type":"dataanalyzer" |                                        |                                           |                           |                       | "analysis.nodeCondition":"type=='bigdata'"  |
#      | com.asg.dis.ingestion.Hdfs                    | BigDataAnalyzer                | Description: Calculates statistics and does pattern matching                        | Supported technologies: Big Data, Hive, Hadoop Files      | Type of analyzer: dataanalyzer | IDA Node restrictions: type=='bigdata'  | "description":{"":"Calculates statistics and does pattern matching"}                        | "analysis.technologies":["Big Data",["Hive","Hadoop Files"]]    | "analysis.type":"dataanalyzer" |                                        |                                           |                           |                       | "analysis.nodeCondition":"type=='bigdata'"  |
#      | com.asg.dis.ingestion.Hdfs                    | HdfsCataloger                  | Description: Retrieves HDFS metadata                                                | Supported technologies: Big Data, Hadoop Files            | Type of analyzer: cataloger    | IDA Node restrictions: type=='bigdata'  | "description":{"":"Retrieves HDFS metadata"}                                                | "analysis.technologies":["Big Data","Hadoop Files"]             | "analysis.type":"cataloger"    |                                        |                                           |                           |                       | "analysis.nodeCondition":"type=='bigdata'"  |
#      | com.asg.dis.ingestion.Hdfs                    | HdfsMonitor                    | Description: Monitors HDFS for changes in files and directories                     | Supported technologies: Big Data, Hadoop Files            | Type of analyzer: monitor      | IDA Node restrictions: type=='bigdata'  | "description":{"":"Retrieves HDFS metadata"}                                                | "analysis.technologies":["Big Data","Hadoop Files"]             | "analysis.type":"monitor"      |                                        |                                           |                           |                       | "analysis.nodeCondition":"type=='bigdata'"  |
#      | com.asg.dis.ingestion.Hive                    | HiveCataloger                  | Description: Retrieves Hive metadata                                                | Supported technologies: Big Data, Hive                    | Type of analyzer: cataloger    | IDA Node restrictions: type=='bigdata'  | "description":{"":"Retrieves Hive metadata"}                                                | "analysis.technologies":["Big Data","Hive"]                     | "analysis.type":"cataloger"    |                                        |                                           |                           |                       | "analysis.nodeCondition":"type=='bigdata'"  |
#      | com.asg.dis.ingestion.Hive                    | HiveMonitor                    | Description: Monitors Hive for changes in tables                                    | Supported technologies: Big Data, Hive                    | Type of analyzer: monitor      | IDA Node restrictions: type=='bigdata'  | "description":{"":"Monitors Hive for changes in tables"}                                    | "analysis.technologies":["Big Data","Hive"]                     | "analysis.type":"monitor"      |                                        |                                           |                           |                       | "analysis.nodeCondition":"type=='bigdata'"  |
#      | com.asg.dis.ingestion.Hive                    | BigDataAnalyzer                | Description: Calculates statistics and does pattern matching                        | Supported technologies: Big Data, Hive, Hadoop Files      | Type of analyzer: dataanalyzer | IDA Node restrictions: type=='bigdata'  | "description":{"":"Calculates statistics and does pattern matching"}                        | "analysis.technologies":["Big Data",["Hive","Hadoop Files"]]    | "analysis.type":"dataanalyzer" |                                        |                                           |                           |                       | "analysis.nodeCondition":"type=='bigdata'"  |
#      | com.asg.dis.ingestion.Hive                    | HiveQueryParser                | Description: Parses Hive queries                                                    | Supported technologies: Big Data, Hive                    | Type of analyzer: parser       | IDA Node restrictions: type=='bigdata'  | "description":{"":"Parses Hive queries"}                                                    | "analysis.technologies":["Big Data","Hive"]                     | "analysis.type":"parser"       |                                        |                                           |                           |                       | "analysis.nodeCondition":"type=='bigdata'"  |
#      | com.asg.dis.platform.CatalogLinker            | HiveDirectoryLinker            | Description: links Hive tables and HDFS directories that contain them               | Supported technologies: Big Data, Hive, Hadoop Files      | Type of analyzer: linker       |                                         | "description":{"":"links Hive tables and HDFS directories that contain them"}               | "analysis.technologies":["Big Data",["Hive","Hadoop Files"]]    | "analysis.type":"linker"       |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.platform.CatalogLinker            | CommonLineage                  | Description: Calculate lineage generically on ASTM tree                             | Supported technologies: Programming, Generic              | Type of analyzer: lineage      |                                         | "description":{"":"Calculate lineage generically on ASTM tree"}                             | "analysis.technologies":["Programming","Generic"]               | "analysis.type":"lineage"      |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.platform.CatalogLinker            | CommonLinker                   | Description: Calculate links generically on ASTM tree                               | Supported technologies: Programming, Generic              | Type of analyzer: linker       |                                         | "description":{"":"Calculate links generically on ASTM tree"}                               | "analysis.technologies":["Programming","Generic"]               | "analysis.type":"linker"       |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.LocalFileCollector       | LocalFileCollector             | Description: Collect sources from a local folder                                    | Supported technologies: Data Files, Local Files           | Type of analyzer: collector    |                                         | "description":{"":"Collect sources from a local folder"}                                    | "analysis.technologies":["Data Files","Local Files"]            | "analysis.type":"collector"    |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.Git                      | GitCollector                   | Description: Collect sources from Git                                               | Supported technologies: Source Control, Git               | Type of analyzer: collector    |                                         | "description":{"":"Collect sources from Git"}                                               | "analysis.technologies":["Source Control","Git"]                | "analysis.type":"collector"    |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.ingestion.UploadHive              | UploadHive                     | Description: Uploads Excel data to Hive tables                                      | Supported technologies: Big Data, Hive                    | Type of analyzer: uploader     | IDA Node restrictions: type=='bigdata'  | "description":{"":"Uploads Excel data to Hive tables"}                                      | "analysis.technologies":["Big Data","Hive"]                     | "analysis.type":"uploader"     |                                        |                                           |                           |                       |                                             |
##     | com.asg.dis.analysis.ExplicitLineage    | ExplicitLineage          | Description: Allow stitching of lineage hops                          | Supported technologies: Programming, Generic              | Type of analyzer: lineage      | {"description":{"":"Allow stitching of lineage hops"}                          | "analysis.technologies":["Programming","Generic"]              | "analysis.type":"lineage"      |                                        |                                           |                            |                                |
#      | com.asg.dis.platform.SimilarityLinker         | SimilarityLinker               | Description: Generic similarity detector                                            |                                                           | Type of analyzer: linker       |                                         | "description":{"":"Generic similarity detector"}                                            |                                                                 | "analysis.type":"linker"       |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.Mobius                   | MobiusCataloger                | Description: Retrieves Mobius metadata                                              | Supported technologies: Data Archives, Mobius             | Type of analyzer: cataloger    |                                         | "description":{"":"Retrieves Mobius metadata"}                                              | "analysis.technologies":["Data Archives","Mobius"]              | "analysis.type":"cataloger"    |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.Mobius                   | MobiusAnalyzer                 | Description: Analyzes Mobius documents                                              | Supported technologies: Data Archives, Mobius             | Type of analyzer: dataanalyzer |                                         | "description":{"":"Analyzes Mobius documents"}                                              | "analysis.technologies":["Data Archives","Mobius"]              | "analysis.type":"dataanalyzer" |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.Oracle-JDBC              | OracleJDBCCataloger            | Description: JDBC Cataloger                                                         | Supported technologies: Relational Databases, Oracle      | Type of analyzer: cataloger    |                                         | "description":{"":"JDBC Cataloger"}                                                         | "analysis.technologies":["Relational Databases","Oracle"]       | "analysis.type":"cataloger"    |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.Oracle-JDBC              | OracleJDBCAnalyzer             | Description: JDBC Analyzer                                                          | Supported technologies: Relational Databases, Oracle      | Type of analyzer: dataanalyzer |                                         | "description":{"":"JDBC Analyzer"}                                                          | "analysis.technologies":["Relational Databases","Oracle"]       | "analysis.type":"dataanalyzer" |                                        |                                           | Supported extensions: sql |                       |                                             |
#      | com.asg.dis.analysis.Postgres-JDBC            | PostgresJDBCCataloger          | Description: JDBC Cataloger                                                         | Supported technologies: Relational Databases, Postgres    | Type of analyzer: cataloger    |                                         | "description":{"":"JDBC Cataloger"}                                                         | "analysis.technologies":["Relational Databases","Postgres"]     | "analysis.type":"cataloger"    |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.Postgres-JDBC            | PostgresJDBCAnalyzer           | Description: JDBC Analyzer                                                          | Supported technologies: Relational Databases, Postgres    | Type of analyzer: dataanalyzer |                                         | "description":{"":"JDBC Analyzer"}                                                          | "analysis.technologies":["Relational Databases","Postgres"]     | "analysis.type":"dataanalyzer" |                                        |                                           | Supported extensions: sql |                       |                                             |
#      | com.asg.dis.analysis.TeraData-JDBC            | TeraDataJDBCCataloger          | Description: JDBC Cataloger                                                         | Supported technologies: Relational Databases, Teradata    | Type of analyzer: cataloger    |                                         | "description":{"":"JDBC Cataloger"}                                                         | "analysis.technologies":["Relational Databases","Teradata"]     | "analysis.type":"cataloger"    |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.TeraData-JDBC            | TeraDataJDBCAnalyzer           | Description: JDBC Analyzer                                                          | Supported technologies: Relational Databases, Teradata    | Type of analyzer: dataanalyzer |                                         | "description":{"":"JDBC Analyzer"}                                                          | "analysis.technologies":["Relational Databases","Teradata"]     | "analysis.type":"dataanalyzer" |                                        |                                           | Supported extensions: sql |                       |                                             |
#      | com.asg.dis.analysis.DB2-JDBC                 | DB2JDBCCataloger               | Description: DB2 JDBC Cataloger                                                     | Supported technologies: Relational Databases, DB2         | Type of analyzer: cataloger    |                                         | "description":{"":"DB2 JDBC Cataloger"}                                                     | "analysis.technologies":["Relational Databases","DB2"]          | "analysis.type":"cataloger"    |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.DB2-JDBC                 | DB2JDBCAnalyzer                | Description: DB2 JDBC Analyzer                                                      | Supported technologies: Relational Databases, DB2         | Type of analyzer: dataanalyzer |                                         | "description":{"":"DB2 JDBC Analyzer"}                                                      | "analysis.technologies":["Relational Databases","DB2"]          | "analysis.type":"dataanalyzer" |                                        |                                           | Supported extensions: sql |                       |                                             |
#      | com.asg.dis.analysis.JDBC                     | JDBCCataloger                  | Description: JDBC Cataloger                                                         | Supported technologies: Relational Databases, JDBC        | Type of analyzer: cataloger    |                                         | {"description":{"":"JDBC Cataloger"}                                                        | "analysis.technologies":["Relational Databases","JDBC"]         | "analysis.type":"cataloger"    |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.JDBC                     | JDBCAnalyzer                   | Description: JDBC Analyzer                                                          | Supported technologies: JDBC, Data Analyzer               | Type of analyzer: dataanalyzer |                                         | "description":{"":"JDBC Analyzer"}                                                          | "analysis.technologies":["JDBC","Data Analyzer"]                | "analysis.type":"dataanalyzer" |                                        |                                           | Supported extensions: sql |                       |                                             |
#      | com.asg.dis.adu.EDIBus                        | EDIBus                         | Description: Transfers data between CoreDI and new DI                               |                                                           | Type of analyzer: bulk         | IDA Node restrictions: type=='internal' | "description":{"":"Transfers data between CoreDI and new DI"}                               |                                                                 |                                |                                        |                                           |                           |                       | "analysis.nodeCondition":"type=='internal'" |
##      | com.asg.dis.platform.Notebook                 | NotebookAnalyzer         |                                                                       |                                                           | Type of analyzer: dataanalyzer |                                                                                |                                                                | "analysis.type":"dataanalyzer" |                                        |                                           |                     |                               |
#      | com.asg.dis.analysis.Python                   | PythonSparkLineage             | Description: Python Spark Lineage                                                   | Supported technologies: Programming, Spark                | Type of analyzer: lineage      |                                         | "description":{"":"Python Spark Lineage"}                                                   | "analysis.technologies":["Programming","Spark"]                 | "analysis.type":"lineage"      |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.Python                   | PythonImportLinker             | Description: Python Linker resolving imports                                        | Supported technologies: Programming, Python               | Type of analyzer: linker       |                                         | "description":{"":"Python Linker resolving imports"}                                        | "analysis.technologies":["Programming","Python"]                | "analysis.type":"linker"       | Supported content types: text/x-python | "analysis.contenttypes":["text/x-python"] |                           |                       |                                             |
#      | com.asg.dis.analysis.Python                   | PythonUseFunctionLinker        | Description: Python Linker between functions                                        | Supported technologies: Programming, Python               | Type of analyzer: linker       |                                         | "description":{"":"Python Linker between functions"}                                        | "analysis.technologies":["Programming","Python"]                | "analysis.type":"linker"       | Supported content types: text/x-python | "analysis.contenttypes":["text/x-python"] |                           |                       |                                             |
#      | com.asg.dis.analysis.Python                   | PythonPackageLinker            | Description: Python Linker between packages                                         | Supported technologies: Programming, Python               | Type of analyzer: linker       |                                         | "description":{"":"Python Linker between packages"}                                         | "analysis.technologies":["Programming","Python"]                | "analysis.type":"linker"       | Supported content types: text/x-python | "analysis.contenttypes":["text/x-python"] |                           |                       |                                             |
#      | com.asg.dis.analysis.Python                   | PythonParser                   | Description: Python Parser                                                          | Supported technologies: Programming, Python               | Type of analyzer: parser       |                                         | "description":{"":"Python Parser"}                                                          | "analysis.technologies":["Programming","Python"]                | "analysis.type":"parser"       | Supported content types: text/x-python | "analysis.contenttypes":["text/x-python"] |                           |                       |                                             |
#      | com.asg.dis.ingestion.ParquetAnalyzer         | ParquetAnalyzer                | Description: Calculates statistics and does pattern matching                        | Supported technologies: Big Data, Parquet, HDFS           | Type of analyzer: dataanalyzer | IDA Node restrictions: type=='bigdata'  | "description":{"":"Calculates statistics and does pattern matching"}                        | "analysis.technologies":["Big Data",["Parquet","Hadoop Files"]] | "analysis.type":"dataanalyzer" |                                        |                                           |                           |                       | "analysis.nodeCondition":"type=='bigdata'"  |
#      | com.asg.dis.analysis.AmazonRedshift           | AmazonRedshiftCataloger        | Description: Redshift Cataloger                                                     | Supported technologies: Cloud Data, Redshift              | Type of analyzer: cataloger    |                                         | "description":{"":"Redshift Cataloger"}                                                     | "analysis.technologies":["Cloud Data","Redshift"]               | "analysis.type":"cataloger"    |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.AmazonRedshift           | AmazonRedshiftAnalyzer         | Description: Redshift Analyzer                                                      | Supported technologies: Cloud Data, Redshift              | Type of analyzer: dataanalyzer |                                         | "description":{"":"Redshift Analyzer"}                                                      | "analysis.technologies":["Cloud Data","Redshift"]               | "analysis.type":"dataanalyzer" |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.AmazonS3                 | AmazonS3Cataloger              | Description: Amazon S3 Cataloger                                                    | Supported technologies: Cloud Data, Amazon S3             | Type of analyzer: cataloger    |                                         | "description":{"":"Amazon S3 Cataloger"}                                                    | "analysis.technologies":["Cloud Data","Amazon S3"]              | "analysis.type":"cataloger"    |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.AzureCosmosDatabase      | AzureCosmosCataloger           | Description: Azure Cosmos Cataloger                                                 | Supported technologies: Cloud Data, Azure Cosmos          | Type of analyzer: cataloger    |                                         | "description":{"":"Azure Cosmos Cataloger"}                                                 | "analysis.technologies":["Cloud Data","Azure Cosmos"]           | "analysis.type":"cataloger"    |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.Cdap                     | CdapCataloger                  | Description: Retrieves Cdap metadata                                                | Supported technologies: Big Data, CDAP                    | Type of analyzer: cataloger    |                                         | "description":{"":"Retrieves Cdap metadata"}                                                | "analysis.technologies":["Big Data","CDAP"]                     | "analysis.type":"cataloger"    |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.Cdap                     | CdapAnalyzer                   | Description: Analyze Cdap data                                                      | Supported technologies: Big Data, CDAP                    | Type of analyzer: dataanalyzer |                                         | "description":{"":"Analyze Cdap data"}                                                      | "analysis.technologies":["Big Data","CDAP"]                     | "analysis.type":"dataanalyzer" |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.CNavigator               | CNavigatorCataloger            | Description: Retrieves metadata and lineage information from Cloudera Navigator API | Supported technologies: Big Data, Cloudera Navigator      | Type of analyzer: cataloger    |                                         | "description":{"":"Retrieves metadata and lineage information from Cloudera Navigator API"} | "analysis.technologies":["Big Data","Cloudera Navigator"]       | "analysis.type":"cataloger"    |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.JsonS3                   | JsonS3Cataloger                | Description: JSON S3 Cataloger                                                      | Supported technologies: Data Files, JSON                  | Type of analyzer: cataloger    |                                         | "description":{"":"JSON S3 Cataloger"}                                                      | "analysis.technologies":["Data Files","JSON"]                   | "analysis.type":"cataloger"    |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.AmazonSpectrum           | AmazonSpectrumCataloger        | Description: Amazon Spectrum Cataloger                                              | Supported technologies: Cloud Data, Redshift Spectrum     | Type of analyzer: cataloger    |                                         | "description":{"":"Amazon Spectrum Cataloger"}                                              | "analysis.technologies":["Cloud Data","Redshift Spectrum"]      | "analysis.type":"cataloger"    |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.AmazonSpectrum           | AmazonSpectrumAnalyzer         | Description: Amazon Spectrum Analyzer                                               | Supported technologies: Cloud Data, Redshift Spectrum     | Type of analyzer: dataanalyzer |                                         | "description":{"":"Amazon Spectrum Analyzer"}                                               | "analysis.technologies":["Cloud Data","Redshift Spectrum"]      | "analysis.type":"dataanalyzer" |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.AmazonSpectrum           | AmazonSpectrumLinker           | Description: Amazon Spectrum Linker                                                 | Supported technologies: Cloud Data, Redshift Spectrum     | Type of analyzer: linker       |                                         | "description":{"":"Amazon Spectrum Linker"}                                                 | "analysis.technologies":["Cloud Data","Redshift Spectrum"]      | "analysis.type":"linker"       |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.AzureSQLDatabase         | AzureSQLDatabaseCataloger      | Description: Azure SQL Database Cataloger                                           | Supported technologies: Cloud Data, Azure SQL DB          | Type of analyzer: cataloger    |                                         | "description":{"":"Azure SQL Database Cataloger"}                                           | "analysis.technologies":["Cloud Data","Azure SQL DB"]           | "analysis.type":"cataloger"    |                                        |                                           |                           |                       |                                             |
#      | com.asg.dis.analysis.AzureSQLDataWarehouse    | AzureSQLDataWarehouseCataloger | Description: Azure SQL Database Cataloger                                           | Supported technologies: Cloud Data, Azure SQL DW          | Type of analyzer: cataloger    |                                         | "description":{"":"Azure SQL Database Cataloger"}                                           | "analysis.technologies":["Cloud Data","Azure SQL DW"]           | "analysis.type":"cataloger"    |                                        |                                           |                           |                       |                                             |
#
#
#
#
